// mock.js — 英语学习工作台 · 数据源（全局变量，无需 export）
// 后续接入真实后端时，只需将以下对象替换为 API 返回结果即可。

// ---------- 用户画像 ----------
const userProfile = {
  name: "同学",
  grade: "大二",
  level: "四级约 140 分（基础较薄弱）",
  vocabEstimate: "约 1800",
  weakSkills: ["听力", "阅读", "写作", "口语"],
  dailyMinutes: 30,
  targetExam: "CET-4 四级",
  interests: ["英文歌曲", "游戏", "影视片段"],
  examDate: "2026-12 中旬",
  startScore: 140,
  goalScore: 380,
};

// ---------- 1. SMART 目标 & 周里程碑 ----------
const smartGoal = {
  S: "将四级听力短对话正确率从约 30% 提升至 60%，阅读细节题正确率从 25% 提升至 55%，总分从 140 提升至 380+。",
  M: "每周完成 2 套真题片段（听力+阅读各 1 套），记录正确率；每周新增掌握 40 个高频词并在词汇库打卡。",
  A: "每天投入 30 分钟，周末可加至 45 分钟。",
  R: "直接对应 2026 年 12 月四级考试，先夯实基础再冲刺及格线。",
  T: "未来 12 周（2026-09-24 至 2026-12-15）达成。",
};

const milestones = [
  { week: 1,  title: "基础词汇打底 + 听力辨音",      target: "掌握 40 词；能听懂数字/时间/地点", done: false },
  { week: 2,  title: "听力短对话入门",              target: "短对话正确率 ≥ 40%",               done: false },
  { week: 3,  title: "阅读细节题突破",              target: "细节题正确率 ≥ 40%",               done: false },
  { week: 4,  title: "听力长对话 + 写作开头模板",    target: "长对话听懂主旨；背熟 3 个开头句",  done: false },
  { week: 5,  title: "阅读推断题 + 写作主体段",      target: "推断题正确率 ≥ 35%；背熟 3 个主体句", done: false },
  { week: 6,  title: "听力篇章 + 写作结尾模板",      target: "篇章听出关键信息；背熟 3 个结尾句", done: false },
  { week: 7,  title: "阅读主旨题 + 翻译简单句",      target: "主旨题正确率 ≥ 50%；翻译 5 句",    done: false },
  { week: 8,  title: "口语日常话题 + 写作仿写",      target: "能用 5 句描述家乡/爱好",           done: false },
  { week: 9,  title: "综合套题（一）",              target: "完整做 1 套真题，计时",             done: false },
  { week: 10, title: "综合套题（二）+ 错题整理",    target: "错题归类，正确率较上周 +10%",      done: false },
  { week: 11, title: "全真模考",                    target: "模考分数 ≥ 340",                   done: false },
  { week: 12, title: "查漏补缺 + 考前冲刺",          target: "高频词过 2 遍；听力保持手感",        done: false },
];

// ---------- 2. 每日任务卡 ----------
const weeklyTasks = [
  { day: "周一", focus: "听力 + 词汇", tasks: [
    { time: "10 分钟", content: "精听 1 段四级短对话（先盲听→看原文→跟读）", type: "听力" },
    { time: "10 分钟", content: "学习 8 个高频词，抄写例句并朗读", type: "词汇" },
    { time: "10 分钟", content: "复习昨天的 8 个词，遮住中文回忆词义", type: "复习" },
  ]},
  { day: "周二", focus: "阅读 + 词汇", tasks: [
    { time: "12 分钟", content: "精读 1 篇四级阅读（标出不懂的词，先猜后查）", type: "阅读" },
    { time: "10 分钟", content: "学习 8 个高频词", type: "词汇" },
    { time: "8 分钟",  content: "把阅读中遇到的生词加入词汇库", type: "词汇" },
  ]},
  { day: "周三", focus: "听力 + 写作", tasks: [
    { time: "10 分钟", content: "精听 1 段听力，做听写练习（写关键词）", type: "听力" },
    { time: "10 分钟", content: "学习 1 个写作开头模板，仿写 1 句", type: "写作" },
    { time: "10 分钟", content: "学习 6 个高频词 + 复习前两天的词", type: "词汇" },
  ]},
  { day: "周四", focus: "阅读 + 口语", tasks: [
    { time: "12 分钟", content: "精读 1 篇阅读，尝试用中文复述大意", type: "阅读" },
    { time: "10 分钟", content: "跟读影视片段 3 遍（模仿语音语调）", type: "口语" },
    { time: "8 分钟",  content: "学习 6 个高频词", type: "词汇" },
  ]},
  { day: "周五", focus: "复盘 + 词汇", tasks: [
    { time: "15 分钟", content: "填写复盘日志三问（做到了什么/卡在哪里/下周怎么调）", type: "复盘" },
    { time: "10 分钟", content: "复习本周所有高频词，标记仍不熟的词", type: "词汇" },
    { time: "5 分钟",  content: "规划下周任务，更新里程碑状态", type: "计划" },
  ]},
  { day: "周六", focus: "模考 + 素材", tasks: [
    { time: "20 分钟", content: "做 1 套真题片段（听力 1 篇 + 阅读 1 篇），记录正确率", type: "模考" },
    { time: "10 分钟", content: "精听 1 首英文歌或影视片段，对照歌词/字幕", type: "素材" },
  ]},
  { day: "周日", focus: "复习 + 轻松输入", tasks: [
    { time: "15 分钟", content: "复习本周全部高频词和错题", type: "复习" },
    { time: "15 分钟", content: "看 1 段游戏/影视英文视频（放松输入）", type: "素材" },
  ]},
];

// ---------- 3. 词汇库 ----------
const vocabLists = [
  { id: "cet4-high", name: "四级高频词", desc: "四级最常考的 500 词精选" },
  { id: "cet4-core", name: "四级核心词", desc: "听力阅读高频出现的核心词" },
  { id: "confused",  name: "易混词专练", desc: "形近/义近词对比记忆" },
  { id: "mastered",  name: "已掌握词复习", desc: "已掌握的词，定期回顾防遗忘" },
];

const vocabulary = [
  // ===== 四级高频词（按词频排序，附词根词缀记忆技巧） =====
  { id: 1,  word: "abandon",  phonetic: "/əˈbændən/", meaning: "v. 放弃；抛弃",
    example: "He had to abandon his car in the heavy snow.", exampleCN: "他不得不在大雪中弃车。",
    tip: "a(加强)+band(带子)+on → 把带子解开扔了 → 抛弃", list: "cet4-high", category: "high" },
  { id: 2,  word: "ability",  phonetic: "/əˈbɪləti/", meaning: "n. 能力；才能",
    example: "She has the ability to learn new things quickly.", exampleCN: "她有快速学习新事物的能力。",
    tip: "able(能的)+ility(名词后缀) → 能力", list: "cet4-high", category: "high" },
  { id: 3,  word: "absolute", phonetic: "/ˈæbsəluːt/", meaning: "adj. 绝对的；完全的",
    example: "I have absolute trust in my best friend.", exampleCN: "我对我最好的朋友有绝对的信任。",
    tip: "ab(离开)+solut(松开) → 完全松开不受限制 → 绝对的", list: "cet4-high", category: "high" },
  { id: 4,  word: "absorb",   phonetic: "/əbˈzɔːb/", meaning: "v. 吸收；吸引",
    example: "Plants absorb water from the soil.", exampleCN: "植物从土壤中吸收水分。",
    tip: "ab(加强)+sorb(吸) → 吸收", list: "cet4-high", category: "high" },
  { id: 5,  word: "academic", phonetic: "/ˌækəˈdemɪk/", meaning: "adj. 学术的；学业的",
    example: "His academic performance improved a lot this term.", exampleCN: "他这学期的学业表现进步很大。",
    tip: "academy(学院)+ic(形容词后缀) → 学术的", list: "cet4-high", category: "high" },
  { id: 6,  word: "accept",   phonetic: "/əkˈsept/", meaning: "v. 接受；同意",
    example: "I am happy to accept your invitation.", exampleCN: "我很高兴接受你的邀请。",
    tip: "ac(加强)+cept(拿) → 拿过来 → 接受", list: "cet4-high", category: "high" },
  { id: 7,  word: "access",   phonetic: "/ˈækses/", meaning: "n. 通道；使用权 v. 访问",
    example: "All students have access to the school library.", exampleCN: "所有学生都可以使用学校图书馆。",
    tip: "ac(加强)+cess(走) → 走进去 → 通道/访问", list: "cet4-high", category: "high" },
  { id: 8,  word: "accident", phonetic: "/ˈæksɪdənt/", meaning: "n. 事故；意外",
    example: "He was late because of a traffic accident.", exampleCN: "他因为交通事故迟到了。",
    tip: "ac(加强)+cid(落下)+ent → 突然落下的事 → 事故", list: "cet4-high", category: "high" },
  { id: 9,  word: "achieve",  phonetic: "/əˈtʃiːv/", meaning: "v. 实现；达到",
    example: "If you work hard, you will achieve your dream.", exampleCN: "如果你努力，你会实现梦想。",
    tip: "a(到)+chieve(头) → 走到头 → 达到目标", list: "cet4-high", category: "high" },
  { id: 10, word: "acquire",  phonetic: "/əˈkwaɪə(r)/", meaning: "v. 获得；学到",
    example: "She acquired a lot of knowledge from reading.", exampleCN: "她从阅读中获得了很多知识。",
    tip: "ac(加强)+quire(寻求) → 寻求得到 → 获得", list: "cet4-high", category: "high" },
  { id: 11, word: "adapt",    phonetic: "/əˈdæpt/", meaning: "v. 适应；改编",
    example: "It takes time to adapt to a new environment.", exampleCN: "适应新环境需要时间。",
    tip: "ad(向)+apt(适合) → 使适合 → 适应", list: "cet4-core", category: "high" },
  { id: 12, word: "adequate", phonetic: "/ˈædɪkwət/", meaning: "adj. 足够的；适当的",
    example: "We have adequate food for the whole week.", exampleCN: "我们有足够吃一整周的食物。",
    tip: "ad(加强)+equ(相等)+ate → 等量的 → 足够的", list: "cet4-core", category: "high" },
  { id: 13, word: "adjust",   phonetic: "/əˈdʒʌst/", meaning: "v. 调整；适应",
    example: "Please adjust the seat to a comfortable height.", exampleCN: "请把座椅调整到舒适的高度。",
    tip: "ad(向)+just(正确) → 使正确 → 调整", list: "cet4-core", category: "high" },
  { id: 14, word: "admit",    phonetic: "/ədˈmɪt/", meaning: "v. 承认；准许进入",
    example: "He admitted that he made a mistake.", exampleCN: "他承认自己犯了错。",
    tip: "ad(加强)+mit(送) → 送进去 → 准许进入/承认", list: "cet4-core", category: "high" },
  { id: 15, word: "advance",  phonetic: "/ədˈvɑːns/", meaning: "v./n. 前进；进步",
    example: "Technology has advanced rapidly in recent years.", exampleCN: "近年来科技进步迅速。",
    tip: "ad(向前)+vance(走) → 向前走 → 前进", list: "cet4-core", category: "high" },
  { id: 16, word: "advantage", phonetic: "/ədˈvɑːntɪdʒ/", meaning: "n. 优势；有利条件",
    example: "Speaking English is a great advantage in job hunting.", exampleCN: "会说英语在求职中是一大优势。",
    tip: "ad(向前)+vant(走)+age → 走在前面 → 优势", list: "cet4-high", category: "high" },
  { id: 17, word: "afford",   phonetic: "/əˈfɔːd/", meaning: "v. 买得起；承担得起",
    example: "I can't afford to buy a new car now.", exampleCN: "我现在买不起新车。",
    tip: "af(加强)+ford(向前) → 能往前走 → 承担得起", list: "cet4-high", category: "high" },
  { id: 18, word: "agency",   phonetic: "/ˈeɪdʒənsi/", meaning: "n. 代理处；机构",
    example: "She works at a travel agency.", exampleCN: "她在一家旅行社工作。",
    tip: "ag(做)+ency(名词) → 做事的地方 → 机构", list: "cet4-core", category: "high" },
  { id: 19, word: "agenda",   phonetic: "/əˈdʒendə/", meaning: "n. 议程；日程",
    example: "What's on the agenda for today's meeting?", exampleCN: "今天会议的议程是什么？",
    tip: "ag(做)+enda → 要做的事 → 议程", list: "cet4-core", category: "high" },
  { id: 30, word: "allow",    phonetic: "/əˈlaʊ/", meaning: "v. 允许；准许",
    example: "My parents allow me to go out on weekends.", exampleCN: "我父母允许我周末出去。",
    tip: "al(加强)+low(低) → 降低门槛 → 允许", list: "cet4-high", category: "high" },
  { id: 31, word: "amount",   phonetic: "/əˈmaʊnt/", meaning: "n. 数量 v. 总计",
    example: "A large amount of money was spent on the project.", exampleCN: "这个项目花了大量资金。",
    tip: "a(到)+mount(山) → 堆成山 → 数量", list: "cet4-high", category: "high" },
  { id: 32, word: "analyze",  phonetic: "/ˈænəlaɪz/", meaning: "v. 分析；解析",
    example: "We need to analyze the data carefully.", exampleCN: "我们需要仔细分析数据。",
    tip: "ana(分开)+lyze(松) → 松开分解 → 分析", list: "cet4-high", category: "high" },
  { id: 33, word: "ancient",  phonetic: "/ˈeɪnʃənt/", meaning: "adj. 古代的；古老的",
    example: "China has an ancient history of 5000 years.", exampleCN: "中国有五千年古老历史。",
    tip: "anci(老)+ent → 古老的", list: "cet4-core", category: "high" },
  { id: 34, word: "announce", phonetic: "/əˈnaʊns/", meaning: "v. 宣布；通告",
    example: "They announced the winner of the contest.", exampleCN: "他们宣布了比赛的获胜者。",
    tip: "an(加强)+nounce(说) → 大声说 → 宣布", list: "cet4-high", category: "high" },
  { id: 35, word: "annual",   phonetic: "/ˈænjuəl/", meaning: "adj. 每年的；年度的",
    example: "The company holds an annual meeting in December.", exampleCN: "公司每年12月开年会。",
    tip: "ann(年)+ual(形容词) → 每年的", list: "cet4-core", category: "high" },
  { id: 36, word: "anxious",  phonetic: "/ˈæŋkʃəs/", meaning: "adj. 焦虑的；渴望的",
    example: "She felt anxious before the exam.", exampleCN: "考试前她感到焦虑。",
    tip: "anx(苦恼)+ious → 焦虑的", list: "cet4-core", category: "high" },
  { id: 37, word: "apparent", phonetic: "/əˈpærənt/", meaning: "adj. 明显的；表面上的",
    example: "It became apparent that he was lying.", exampleCN: "很明显他在撒谎。",
    tip: "ap(加强)+par(出现)+ent → 出现的 → 明显的", list: "cet4-core", category: "high" },
  { id: 38, word: "appeal",   phonetic: "/əˈpiːl/", meaning: "v./n. 呼吁；吸引；上诉",
    example: "The idea appeals to young people.", exampleCN: "这个想法吸引年轻人。",
    tip: "ap(向)+peal(推动) → 推向某人 → 呼吁/吸引", list: "cet4-core", category: "high" },
  { id: 39, word: "apply",    phonetic: "/əˈplaɪ/", meaning: "v. 申请；应用",
    example: "You should apply for the job before Friday.", exampleCN: "你应该在周五前申请这份工作。",
    tip: "ap(向)+ply(折叠) → 折叠投向 → 申请/应用", list: "cet4-high", category: "high" },
  { id: 50, word: "approach", phonetic: "/əˈprəʊtʃ/", meaning: "v. 接近 n. 方法",
    example: "We need a new approach to solve this problem.", exampleCN: "我们需要新方法解决这个问题。",
    tip: "ap(向)+proach(近) → 走近 → 接近/方法", list: "cet4-high", category: "high" },
  { id: 51, word: "approve",  phonetic: "/əˈpruːv/", meaning: "v. 赞成；批准",
    example: "My parents approved of my decision.", exampleCN: "我父母赞成我的决定。",
    tip: "ap(加强)+prove(证明) → 证明可行 → 批准", list: "cet4-core", category: "high" },
  { id: 52, word: "argue",    phonetic: "/ˈɑːɡjuː/", meaning: "v. 争论；主张",
    example: "They argued about money for hours.", exampleCN: "他们为钱争论了几个小时。",
    tip: "arg(银/白)+ue → 辩白 → 争论", list: "cet4-core", category: "high" },
  { id: 53, word: "arrange",  phonetic: "/əˈreɪndʒ/", meaning: "v. 安排；整理",
    example: "I will arrange a meeting for tomorrow.", exampleCN: "我会安排明天的会议。",
    tip: "ar(加强)+range(排列) → 排列好 → 安排", list: "cet4-high", category: "high" },
  { id: 54, word: "arrest",   phonetic: "/əˈrest/", meaning: "v./n. 逮捕；阻止",
    example: "The police arrested the thief last night.", exampleCN: "警察昨晚逮捕了小偷。",
    tip: "ar(加强)+rest(休息) → 让人休息(停下) → 逮捕", list: "cet4-core", category: "high" },
  { id: 55, word: "arrive",   phonetic: "/əˈraɪv/", meaning: "v. 到达",
    example: "The train arrives at 8 o'clock.", exampleCN: "火车8点到达。",
    tip: "ar(向)+rive(岸) → 到岸 → 到达", list: "cet4-high", category: "high" },
  { id: 56, word: "article",  phonetic: "/ˈɑːtɪkl/", meaning: "n. 文章；物品；冠词",
    example: "She wrote an article for the newspaper.", exampleCN: "她为报纸写了一篇文章。",
    tip: "art(技艺)+icle(小) → 小技艺作品 → 文章", list: "cet4-high", category: "high" },
  { id: 57, word: "artificial", phonetic: "/ˌɑːtɪˈfɪʃl/", meaning: "adj. 人造的；假的",
    example: "This flower is artificial, not real.", exampleCN: "这朵花是人造的，不是真的。",
    tip: "arti(技艺)+fic(做)+ial → 用技艺做的 → 人造的", list: "cet4-core", category: "high" },
  { id: 58, word: "aspect",   phonetic: "/ˈæspekt/", meaning: "n. 方面；外观",
    example: "We should consider every aspect of the problem.", exampleCN: "我们应该考虑问题的每个方面。",
    tip: "a(向)+spect(看) → 看的方向 → 方面", list: "cet4-high", category: "high" },
  { id: 59, word: "assess",   phonetic: "/əˈses/", meaning: "v. 评估；估价",
    example: "The teacher will assess our writing skills.", exampleCN: "老师会评估我们的写作能力。",
    tip: "as(靠近)+sess(坐) → 坐下来判断 → 评估", list: "cet4-core", category: "high" },
  { id: 60, word: "assign",   phonetic: "/əˈsaɪn/", meaning: "v. 分配；指派",
    example: "The teacher assigned homework to the class.", exampleCN: "老师给全班布置了作业。",
    tip: "as(加强)+sign(标记) → 标记分配 → 指派", list: "cet4-core", category: "high" },
  { id: 61, word: "assist",   phonetic: "/əˈsɪst/", meaning: "v. 帮助；协助",
    example: "She assisted me with my English study.", exampleCN: "她帮助我学英语。",
    tip: "as(靠近)+sist(站) → 站在旁边 → 协助", list: "cet4-core", category: "high" },
  { id: 62, word: "associate", phonetic: "/əˈsəʊsieɪt/", meaning: "v. 联想；交往 n. 同事",
    example: "I always associate summer with ice cream.", exampleCN: "我总把夏天和冰淇淋联系在一起。",
    tip: "as(加强)+soci(同伴)+ate → 成为同伴 → 联想/交往", list: "cet4-core", category: "high" },
  { id: 63, word: "assume",   phonetic: "/əˈsjuːm/", meaning: "v. 假定；承担",
    example: "I assume you are right about this.", exampleCN: "我假定你在这件事上是对的。",
    tip: "as(加强)+sume(拿) → 拿来用 → 假定/承担", list: "cet4-high", category: "high" },
  { id: 64, word: "attempt",  phonetic: "/əˈtempt/", meaning: "v./n. 尝试；企图",
    example: "He made an attempt to climb the mountain.", exampleCN: "他尝试爬那座山。",
    tip: "at(向)+tempt(试探) → 试探 → 尝试", list: "cet4-high", category: "high" },
  { id: 65, word: "attend",   phonetic: "/əˈtend/", meaning: "v. 出席；照料",
    example: "All students must attend the meeting.", exampleCN: "所有学生必须出席会议。",
    tip: "at(向)+tend(伸展) → 伸过去 → 出席", list: "cet4-high", category: "high" },
  { id: 66, word: "attitude", phonetic: "/ˈætɪtjuːd/", meaning: "n. 态度；看法",
    example: "A positive attitude helps you succeed.", exampleCN: "积极的态度助你成功。",
    tip: "apt(适合)+itude → 适合的状态 → 态度", list: "cet4-high", category: "high" },
  { id: 67, word: "attract",  phonetic: "/əˈtrækt/", meaning: "v. 吸引；引起",
    example: "The bright colors attract children.", exampleCN: "鲜艳的颜色吸引孩子。",
    tip: "at(加强)+tract(拉) → 拉过来 → 吸引", list: "cet4-high", category: "high" },
  { id: 68, word: "average",  phonetic: "/ˈævərɪdʒ/", meaning: "adj. 平均的 n. 平均数",
    example: "The average age of the class is 19.", exampleCN: "班级平均年龄是19岁。",
    tip: "aver(损坏)+age → 损坏均摊 → 平均", list: "cet4-high", category: "high" },
  { id: 69, word: "avoid",    phonetic: "/əˈvɔɪd/", meaning: "v. 避免；避开",
    example: "Try to avoid making the same mistake.", exampleCN: "尽量避免犯同样的错误。",
    tip: "a(离开)+void(空) → 使空出来 → 避开", list: "cet4-high", category: "high" },
  { id: 70, word: "aware",    phonetic: "/əˈweə(r)/", meaning: "adj. 意识到的；知道的",
    example: "Are you aware of the risk?", exampleCN: "你意识到风险了吗？",
    tip: "a(加强)+ware(注视) → 注视到 → 意识到", list: "cet4-high", category: "high" },

  // ===== 易混词对比 =====
  { id: 20, word: "affect",   phonetic: "/əˈfekt/", meaning: "v. 影响（动词）",
    example: "The cold weather affects my health.", exampleCN: "寒冷的天气影响我的健康。", list: "confused", category: "confused",
    pairWith: "effect", pairTip: "affect 是动词(影响)；effect 是名词(效果/影响)" },
  { id: 21, word: "effect",   phonetic: "/ɪˈfekt/", meaning: "n. 效果；影响（名词）",
    example: "The medicine had a good effect on me.", exampleCN: "这药对我效果很好。", list: "confused", category: "confused",
    pairWith: "affect", pairTip: "effect 是名词；affect 是动词" },
  // 注意：这条与 id 11 是同形词，释义必须与 id 11 区分开，
  // 否则测验时同一个词会出现两个“正确答案”
  { id: 22, word: "adapt",    phonetic: "/əˈdæpt/", meaning: "v. 适应（新环境）；改编（与 adopt 对比记）",
    example: "Children adapt to new schools quickly.", exampleCN: "孩子们很快适应新学校。", list: "confused", category: "confused",
    pairWith: "adopt", pairTip: "adapt = 适应/改编；adopt = 采纳/收养" },
  { id: 23, word: "adopt",    phonetic: "/əˈdɒpt/", meaning: "v. 采纳；收养",
    example: "They decided to adopt a new method.", exampleCN: "他们决定采用一种新方法。", list: "confused", category: "confused",
    pairWith: "adapt", pairTip: "adopt = 采纳/收养；adapt = 适应" },
  { id: 24, word: "principle", phonetic: "/ˈprɪnsəpl/", meaning: "n. 原则；原理",
    example: "He is a man of strong principles.", exampleCN: "他是一个有原则的人。", list: "confused", category: "confused",
    pairWith: "principal", pairTip: "principle = 原则(le结尾)；principal = 校长/主要的" },
  { id: 25, word: "principal", phonetic: "/ˈprɪnsəpl/", meaning: "n. 校长 adj. 主要的",
    example: "The principal gave a speech at the opening.", exampleCN: "校长在开幕式上发表了讲话。", list: "confused", category: "confused",
    pairWith: "principle", pairTip: "principal = 校长/主要的；principle = 原则" },
  { id: 26, word: "complement", phonetic: "/ˈkɒmplɪment/", meaning: "v./n. 补充；补足",
    example: "The two colors complement each other.", exampleCN: "这两种颜色相得益彰。", list: "confused", category: "confused",
    pairWith: "compliment", pairTip: "complement = 补充(e)；compliment = 称赞(i)" },
  { id: 27, word: "compliment", phonetic: "/ˈkɒmplɪmənt/", meaning: "n./v. 称赞；恭维",
    example: "She paid me a compliment on my new dress.", exampleCN: "她称赞了我的新裙子。", list: "confused", category: "confused",
    pairWith: "complement", pairTip: "compliment = 称赞(i)；complement = 补充(e)" },
  { id: 28, word: "economic",  phonetic: "/ˌiːkəˈnɒmɪk/", meaning: "adj. 经济的；经济学的",
    example: "The country is enjoying rapid economic growth.", exampleCN: "该国经济正快速增长。", list: "confused", category: "confused",
    pairWith: "economical", pairTip: "economic = 经济的(宏观)；economical = 节约的" },
  { id: 29, word: "economical", phonetic: "/ˌiːkəˈnɒmɪkl/", meaning: "adj. 节约的；经济实惠的",
    example: "This small car is very economical on fuel.", exampleCN: "这辆小车非常省油。", list: "confused", category: "confused",
    pairWith: "economic", pairTip: "economical = 节约的；economic = 经济的" },

  // ===== 已掌握（示例） =====
  { id: 40, word: "the",    phonetic: "/ðə/",   meaning: "art. 这；那",
    example: "The book is on the desk.", exampleCN: "书在桌子上。", list: "mastered", category: "mastered" },
  { id: 41, word: "be",     phonetic: "/biː/",  meaning: "v. 是；存在",
    example: "I want to be a teacher.", exampleCN: "我想成为一名老师。", list: "mastered", category: "mastered" },
  { id: 42, word: "have",   phonetic: "/hæv/",  meaning: "v. 有；吃；喝",
    example: "I have a beautiful cat.", exampleCN: "我有一只漂亮的猫。", list: "mastered", category: "mastered" },
  { id: 43, word: "do",     phonetic: "/duː/",  meaning: "v. 做；干",
    example: "What do you do on weekends?", exampleCN: "你周末做什么？", list: "mastered", category: "mastered" },
];

// ---------- 4. 素材库 ----------
const materials = [
  { week: 1, type: "听力", format: "英文歌曲", title: "Lemon Tree — Fools Garden", level: "★☆☆☆☆ 入门",
    reason: "语速慢、歌词重复、句式简单，适合练辨音和连读。", howToUse: "先盲听 1 遍 → 对照歌词听 2 遍 → 跟着唱 1 遍。", link: "可在网易云/B站搜索" },
  { week: 1, type: "阅读", format: "影视片段", title: "《老友记》S01E01 开头片段", level: "★★☆☆☆ 简单",
    reason: "日常对话多、语速适中、贴近生活。", howToUse: "看中英字幕 1 遍 → 只看英文字幕 1 遍 → 跟读模仿。", link: "B站搜索 老友记 片段" },
  { week: 2, type: "听力", format: "英文歌曲", title: "Yesterday Once More — Carpenters", level: "★☆☆☆☆ 入门",
    reason: "经典老歌，发音清晰，适合精听。", howToUse: "逐句听写关键词，再对照歌词。", link: "网易云/B站" },
  { week: 2, type: "阅读", format: "游戏", title: "Stardew Valley（星露谷物语）英文界面", level: "★★☆☆☆ 简单",
    reason: "游戏文本简单，有图辅助理解，兴趣驱动。", howToUse: "把游戏语言设为英文，遇到不懂的词截图查。", link: "Steam/Switch 游戏内设置" },
  { week: 3, type: "听力", format: "影视片段", title: "《阿甘正传》经典独白片段", level: "★★★☆☆ 中等",
    reason: "发音标准、语速慢，适合模仿。", howToUse: "跟读 5 遍，模仿语音语调。", link: "B站搜索 阿甘正传 独白" },
  { week: 3, type: "阅读", format: "游戏", title: "Minecraft（我的世界）英文 Achievement 文本", level: "★★☆☆☆ 简单",
    reason: "短句、动词多，适合积累动作词汇。", howToUse: "收集成就描述，整理其中的动词。", link: "游戏内成就列表" },
  { week: 4, type: "听力", format: "英文歌曲", title: "Count On Me — Bruno Mars", level: "★★☆☆☆ 简单",
    reason: "温暖积极，词汇实用，适合朗读背诵。", howToUse: "背诵副歌部分，体会连读。", link: "网易云/B站" },
  { week: 4, type: "阅读", format: "影视片段", title: "《疯狂动物城》警局对话片段", level: "★★★☆☆ 中等",
    reason: "对话丰富、有俚语但不多，适合四级水平。", howToUse: "记录 5 个实用表达并造句。", link: "B站搜索 疯狂动物城 片段" },
  { week: 5, type: "听力", format: "影视片段", title: "《哈利·波特与魔法石》分院帽片段", level: "★★★☆☆ 中等",
    reason: "语音标准，词汇丰富，有趣味性。", howToUse: "盲听后复述大意，再对照字幕。", link: "B站搜索 哈利波特 分院帽" },
  { week: 5, type: "阅读", format: "游戏", title: "《原神》英文任务对话选段", level: "★★★☆☆ 中等",
    reason: "剧情文本有一定难度，能拓展词汇。", howToUse: "选一段任务对话，逐句精读。", link: "游戏内将语言设为 English" },

  // ===== 以下为补充素材 =====
  // 为什么补：原池子只有 10 条且「游戏 × 听力」和「英文歌曲 × 阅读」两个格子是 0 条 ——
  // 用户只选「游戏」这一个兴趣时，听力永远是空的。排期算法只排序不硬排除，
  // 所以格子为零会直接暴露成空槽。现在每个（格式 × 类型）格子至少 2 条，共 24 条，
  // 足够 12 周每周 2 条且同一素材间隔 ≥3 周。
  // 注意：`week` 字段已不再用于排期（改由 plan.js 的 pickMaterials 按索引循环），
  // 保留仅为兼容旧数据。link 一律写"去哪里搜/在哪里设置"，不放假链接。

  { week: 1, type: "听力", format: "英文歌曲", title: "Hey Jude — The Beatles", level: "★★☆☆☆ 简单",
    reason: "尾段「na na na」反复出现，节奏慢，特别适合练连读和长音。",
    howToUse: "跟读副歌 3 遍，注意 \"Hey Jude\" 的连读。", link: "网易云/B站搜索" },

  { week: 1, type: "阅读", format: "英文歌曲", title: "Let It Be — The Beatles（歌词精读）", level: "★★☆☆☆ 简单",
    reason: "歌词像一段独白，句子短、重复多，一句话一个意思，适合第一次做歌词精读。",
    howToUse: "把歌词抄一遍，标出所有动词和它们的时态。", link: "网易云/B站搜索歌词" },
  { week: 2, type: "阅读", format: "英文歌曲", title: "Blowing in the Wind — Bob Dylan（歌词精读）", level: "★★★☆☆ 中等",
    reason: "歌词本身就是一首诗，疑问句反复出现，适合练句型和排比。",
    howToUse: "逐句翻译，再找一份中文译本比较差别。", link: "网易云/B站搜索歌词" },
  { week: 3, type: "阅读", format: "英文歌曲", title: "Trouble Is a Friend — Lenka（歌词精读）", level: "★★☆☆☆ 简单",
    reason: "用词日常、比喻直白，适合积累描述情绪的形容词。",
    howToUse: "找出所有形容心情的词，按「好／坏」分成两栏。", link: "网易云/B站搜索歌词" },

  { week: 1, type: "听力", format: "影视片段", title: "《摩登家庭》S01E01 家庭对话片段", level: "★★★☆☆ 中等",
    reason: "多人对话、语速偏快，最接近四级听力长对话的真实难度。",
    howToUse: "先盲听抓大意，再逐句听写，最后对照字幕。", link: "B站搜索 摩登家庭 片段" },
  { week: 2, type: "听力", format: "影视片段", title: "《肖申克的救赎》旁白片段", level: "★★★☆☆ 中等",
    reason: "旁白语速慢、发音清晰、句子完整，适合练长句听写。",
    howToUse: "听写整段旁白，重点抓连接词和从句结构。", link: "B站搜索 肖申克 旁白" },

  { week: 2, type: "阅读", format: "影视片段", title: "《当幸福来敲门》面试对话字幕", level: "★★★☆☆ 中等",
    reason: "面试场景，句子完整、用词正式，适合积累书面表达。",
    howToUse: "把台词抄下来，挑 5 句改写成书面语。", link: "B站搜索 当幸福来敲门 面试片段" },
  { week: 3, type: "阅读", format: "影视片段", title: "《穿普拉达的女王》职场对话片段", level: "★★★★☆ 较难",
    reason: "语速快、俚语多。听力很难跟上，但读字幕来整理俚语很有价值。",
    howToUse: "只读字幕，把不认识的表达整理成清单。", link: "B站搜索 穿普拉达的女王 片段" },

  { week: 1, type: "听力", format: "游戏", title: "Stardew Valley 角色对话语音（英文）", level: "★★☆☆☆ 简单",
    reason: "角色台词短、重复率高、语速慢，是游戏类里最好的入门精听材料。",
    howToUse: "把游戏语言设为英文，遇到对话先听一遍再读字幕。", link: "游戏内设置语言为 English" },
  { week: 2, type: "听力", format: "游戏", title: "Minecraft 成就解锁提示", level: "★★☆☆☆ 简单",
    reason: "单句、无背景噪音，适合练听写数字和动作词。",
    howToUse: "听写 20 条成就描述，核对拼写。", link: "游戏内成就列表（语言设为 English）" },
  { week: 3, type: "听力", format: "游戏", title: "The Sims 4 内嵌旁白 + 英文字幕", level: "★★☆☆☆ 简单",
    reason: "游戏内旁白配英文字幕，语境直观，猜词负担小。",
    howToUse: "先看字幕听一遍，再关字幕听一遍。", link: "游戏内设置字幕为 English" },
  { week: 4, type: "听力", format: "游戏", title: "Portal 2 旁白片段（GLaDOS）", level: "★★★★☆ 较难",
    reason: "台词讽刺、语速快、词汇量大，适合冲刺阶段挑战听力上限。",
    howToUse: "逐句听写，听不懂的先按发音猜，再用字幕核对。", link: "B站搜索 Portal 2 GLaDOS 台词" },

  { week: 3, type: "阅读", format: "游戏", title: "Minecraft 合成说明与 Wiki 词条", level: "★★☆☆☆ 简单",
    reason: "说明书文体，祈使句多，适合积累动词和材料名。",
    howToUse: "挑 10 条合成配方，读出并抄写其中的动词。", link: "游戏内配方界面 / 官方 Wiki" },
  { week: 4, type: "阅读", format: "游戏", title: "Stardew Valley 村民信件与任务文本", level: "★★★☆☆ 中等",
    reason: "书信体，有完整句子和情感表达，适合练阅读理解。",
    howToUse: "每读完一封信，用中文写出大意。", link: "游戏内信箱（语言设为 English）" },
];

// ---------- 5. 复盘日志模板 ----------
const reviewTemplate = {
  questions: [
    { key: "done",  label: "做到了什么", placeholder: "本周完成了哪些任务？掌握了哪些词？正确率有提升吗？" },
    { key: "stuck", label: "卡在哪里",   placeholder: "哪个部分最难？是单词不认识、听不懂、还是读不懂？具体说。" },
    { key: "next",  label: "下周怎么调整", placeholder: "针对卡点，下周打算多练什么、用什么方法？" },
  ],
};
