// practice-data.js — 写作 / 翻译 / 对话 三个模块的内容数据（全局变量）
// 全部离线内置，不依赖任何网络资源。

/* ===================== 写作：模板与范文 ===================== */
const writingTemplates = [
  {
    id: "argument",
    name: "议论文（现象讨论型）",
    desc: "四级写作出现频率最高。结构固定：引出话题 → 分析原因/影响 → 表明态度。按这个框架写，不会跑题。",
    wordTarget: "120-180 词",
    sections: [
      {
        key: "opening", label: "开头段 · 引出话题",
        patterns: [
          { en: "Nowadays, ______ has become a hot topic among college students.",
            cn: "如今，______ 已经成为大学生中的热门话题。",
            note: "最通用的开头，任何话题都能套" },
          { en: "With the rapid development of ______, more and more people begin to pay attention to ______.",
            cn: "随着 ______ 的快速发展，越来越多的人开始关注 ______。",
            note: "适合有明确社会背景的话题（网络、经济、教育）" },
          { en: "There is a growing concern over ______ in recent years.",
            cn: "近年来，人们对 ______ 越来越关注。",
            note: "偏正式，适合带一点批判性的话题" },
        ],
      },
      {
        key: "body", label: "主体段 · 分析论证",
        patterns: [
          { en: "There are several reasons accounting for this phenomenon. First of all, ______. What's more, ______.",
            cn: "造成这一现象的原因有几个。首先，______。此外，______。",
            note: "列举原因，四级最好写两点就够" },
          { en: "It is obvious that ______ plays an important role in ______.",
            cn: "很明显，______ 在 ______ 中起着重要作用。",
            note: "强调重要性，万能句式" },
          { en: "On the one hand, ______. On the other hand, ______.",
            cn: "一方面，______。另一方面，______。",
            note: "两面分析，显得客观" },
          { en: "Take ______ as an example. ______.",
            cn: "以 ______ 为例。______。",
            note: "举例子，但例子不要编得太复杂" },
        ],
      },
      {
        key: "closing", label: "结尾段 · 总结表态",
        patterns: [
          { en: "In conclusion, ______. As long as we ______, we will surely ______.",
            cn: "总之，______。只要我们 ______，就一定能 ______。",
            note: "万能结尾，积极向上" },
          { en: "From what has been discussed above, we can draw the conclusion that ______.",
            cn: "综上所述，我们可以得出结论：______。",
            note: "很稳的收尾句" },
          { en: "Therefore, it is high time that we took measures to ______.",
            cn: "因此，是我们采取措施 ______ 的时候了。",
            note: "注意 it is high time that 后面用过去式" },
        ],
      },
    ],
    model: {
      title: "范文：On the Importance of Reading",
      text: `Nowadays, reading has become a hot topic among college students. With the rapid development of the Internet, more and more people begin to pay attention to how to spend their free time properly.

There are several reasons accounting for the importance of reading. First of all, reading broadens our horizon and helps us understand the world better. What's more, it improves our language ability, which is especially important for English learners like us. Take vocabulary as an example. A student who reads twenty minutes a day can learn far more words than one who merely recites word lists.

In conclusion, reading is worth our time and effort. As long as we keep reading every day, we will surely benefit from it in the long run.`,
      note: "注意范文的三段结构、每段首句的作用，以及 First of all / What's more / Take ... as an example 这些衔接词。",
    },
  },
  {
    id: "letter",
    name: "书信 / 应用文",
    desc: "常见于建议信、求职信、邀请信。格式分要拿满：称呼、正文三段、结尾敬语、署名。",
    wordTarget: "100-150 词",
    sections: [
      {
        key: "opening", label: "称呼与开头",
        patterns: [
          { en: "Dear ______, I am writing to express my ______ concerning ______.",
            cn: "亲爱的 ______：我写信是为了表达我关于 ______ 的 ______。",
            note: "I am writing to... 是书信万能开头，说明目的" },
          { en: "I am very glad to hear that ______. I would like to ______.",
            cn: "很高兴听说 ______。我想 ______。",
            note: "回信、回复类适用" },
        ],
      },
      {
        key: "body", label: "正文 · 具体内容",
        patterns: [
          { en: "To begin with, ______. In addition, ______.",
            cn: "首先，______。此外，______。",
            note: "书信里的分点陈述" },
          { en: "I would like to suggest that you ______, which may help you ______.",
            cn: "我想建议你 ______，这可能会帮你 ______。",
            note: "建议信的核心句式" },
          { en: "If it is convenient for you, please ______.",
            cn: "如果你方便的话，请 ______。",
            note: "礼貌地提出请求" },
        ],
      },
      {
        key: "closing", label: "结尾敬语与署名",
        patterns: [
          { en: "I am looking forward to your early reply.",
            cn: "期待你的早日回复。",
            note: "最常用的结尾" },
          { en: "Thank you for your time and consideration.",
            cn: "感谢你抽出时间考虑。",
            note: "更正式，求职信适用" },
          { en: "Yours sincerely, / Li Ming",
            cn: "你真诚的，/ 李明",
            note: "注意署名要换行，别和敬语连在一起" },
        ],
      },
    ],
    model: {
      title: "范文：建议信 — A Letter of Suggestion",
      text: `Dear Wang Fang,

I am writing to express my suggestions concerning your English study. I am very glad to hear that you have decided to take the CET-4 exam this December.

To begin with, you may find it helpful to build a vocabulary habit, since words are the basis of everything. In addition, listening to short conversations every day will improve your listening step by step. I would like to suggest that you practice reading aloud for ten minutes each morning, which may help you remember sentence patterns naturally.

If it is convenient for you, please tell me your weekly plan so that we can check our progress together. I am looking forward to your early reply.

Yours sincerely,
Li Ming`,
      note: "称呼后有逗号，敬语后也有逗号，署名另起一行 —— 这三处格式分每年都有人丢。",
    },
  },
  {
    id: "chart",
    name: "图表 / 数据描述",
    desc: "给出图表数据，要求描述变化并解释原因。关键是把趋势词用对。",
    wordTarget: "120-180 词",
    sections: [
      {
        key: "opening", label: "开头段 · 描述数据",
        patterns: [
          { en: "As is shown in the chart, the number of ______ increased from ______ to ______.",
            cn: "如图所示，______ 的数量从 ______ 增长到了 ______。",
            note: "描述数据最标准的句式。As is shown in the chart 是固定搭配" },
          { en: "According to the figures given above, there was a sharp rise in ______.",
            cn: "根据上面给出的数据，______ 出现了急剧上升。",
            note: "sharp rise 表示陡增" },
          { en: "The past decade has witnessed a steady decline in ______.",
            cn: "过去十年见证了 ______ 的稳步下降。",
            note: "has witnessed 是图表题高级句式" },
        ],
      },
      {
        key: "body", label: "主体段 · 解释原因",
        patterns: [
          { en: "Several factors contribute to this change. Among them, ______ is the most important one.",
            cn: "有几个因素造成了这一变化。其中，______ 是最重要的一个。",
            note: "contribute to 表示促成" },
          { en: "This trend can be explained by the fact that ______.",
            cn: "这一趋势可以用 ______ 这一事实来解释。",
            note: "把原因放进 that 从句" },
        ],
      },
      {
        key: "closing", label: "结尾段 · 预测或评价",
        patterns: [
          { en: "It can be predicted that this trend will continue in the near future.",
            cn: "可以预测这一趋势在不久的将来会持续。",
            note: "图表题最安全的结尾" },
          { en: "If this trend continues, it will have a great impact on ______.",
            cn: "如果这一趋势持续，将对 ______ 产生重大影响。",
            note: "加一点自己的判断" },
        ],
      },
    ],
    model: {
      title: "范文：The Rise of Online Learning",
      text: `As is shown in the chart, the number of students taking online courses increased from 20 percent in 2020 to 65 percent in 2025. The past five years has witnessed a sharp rise in online learning.

Several factors contribute to this change. Among them, the flexibility of time is the most important one, because students can arrange their study around other commitments. This trend can also be explained by the fact that high-quality courses are now available to anyone with an Internet connection.

It can be predicted that this trend will continue in the near future. If it does, it will have a great impact on the way we learn English.`,
      note: "数据描述题不要求你分析得多深，把趋势说准、原因给两条，分数就稳了。",
    },
  },
];

// 用于自评的常用衔接词小抄
const writingLinkers = [
  { group: "表递进", items: ["First of all", "What's more", "In addition", "Furthermore", "Moreover"] },
  { group: "表转折", items: ["However", "Nevertheless", "On the contrary", "In spite of"] },
  { group: "表因果", items: ["Therefore", "As a result", "Consequently", "Due to", "Owing to"] },
  { group: "表举例", items: ["For instance", "Take ... as an example", "Such as"] },
  { group: "表总结", items: ["In conclusion", "To sum up", "In a word", "From what has been discussed above"] },
];

/* ===================== 翻译：主题句库 ===================== */
const translationThemes = [
  {
    id: "culture",
    name: "中国传统文化",
    desc: "四级翻译最高频的主题，几乎每年都考。重点词：文化遗产、传承、象征。",
    items: [
      { cn: "中国有着五千多年的悠久历史，留下了丰富的文化遗产。",
        en: "China has a long history of more than 5,000 years, leaving a rich cultural heritage.",
        note: "leaving 是现在分词作结果状语，比 and 连两个句子高级" },
      { cn: "春节是中国最重要的传统节日，家人会聚在一起吃年夜饭。",
        en: "The Spring Festival is the most important traditional festival in China, when families get together for the New Year's Eve dinner.",
        note: "用 when 引导定语从句补充说明，避免句子太散" },
      { cn: "越来越多的年轻人开始对中国书法感兴趣。",
        en: "More and more young people are beginning to take an interest in Chinese calligraphy.",
        note: "take an interest in = 对…感兴趣" },
      { cn: "这些传统手工艺需要被保护并传承给下一代。",
        en: "These traditional handicrafts need to be protected and passed on to the next generation.",
        note: "被动语态 need to be done；pass on = 传承" },
      { cn: "丝绸之路不仅促进了贸易，也促进了文化交流。",
        en: "The Silk Road promoted not only trade but also cultural exchange.",
        note: "not only ... but also 的用法，注意连接的部分要平行" },
      { cn: "中秋节象征着团圆，人们在这一天赏月、吃月饼。",
        en: "The Mid-Autumn Festival symbolizes reunion. On this day, people admire the moon and eat mooncakes.",
        note: "中文一句话里两个主语，英文拆成两句更自然" },
      { cn: "京剧被称为中国国粹，已有两百多年的历史。",
        en: "Peking Opera is known as the national treasure of China, with a history of over 200 years.",
        note: "be known as = 被称为；with 表伴随" },
      { cn: "如今，许多外国人对中国文化产生了浓厚的兴趣。",
        en: "Nowadays, many foreigners have developed a strong interest in Chinese culture.",
        note: "develop an interest in 比 be interested in 更书面" },
    ],
  },
  {
    id: "festival",
    name: "节日与习俗",
    desc: "常与传统文化一起考。注意日期表达和习俗动词。",
    items: [
      { cn: "端午节在农历五月初五，人们通过赛龙舟来纪念屈原。",
        en: "The Dragon Boat Festival falls on the fifth day of the fifth lunar month, when people commemorate Qu Yuan by holding dragon boat races.",
        note: "fall on 表示（节日）在某一日；by doing 表方式" },
      { cn: "元宵节那天，街上到处挂着彩灯。",
        en: "On the Lantern Festival, colorful lanterns are hung everywhere in the streets.",
        note: "被动语态 + everywhere 位置" },
      { cn: "按照传统，人们在春节期间会给孩子们发红包。",
        en: "According to tradition, people give children red envelopes during the Spring Festival.",
        note: "According to tradition 是很好的开头" },
      { cn: "这个节日的习俗已经流传了几百年。",
        en: "The customs of this festival have been passed down for hundreds of years.",
        note: "现在完成时 + for 时间段" },
      { cn: "无论多忙，家人都会尽量在节日团聚。",
        en: "No matter how busy they are, family members try their best to get together during the festival.",
        note: "No matter how + 形容词，是很实用的让步结构" },
      { cn: "清明节是人们祭扫祖先、缅怀先人的日子。",
        en: "The Qingming Festival is a day when people visit the graves of their ancestors to pay their respects.",
        note: "is a day when 是定义式表达" },
      { cn: "不同地区的庆祝方式各不相同。",
        en: "Ways of celebration vary from region to region.",
        note: "vary from ... to ... 表各不相同" },
      { cn: "这些习俗反映了中国人对家庭的重视。",
        en: "These customs reflect Chinese people's emphasis on family.",
        note: "emphasis on = 对…的重视" },
    ],
  },
  {
    id: "geography",
    name: "地理与旅游",
    desc: "常考景点、河流、城市介绍。注意数字和方位表达。",
    items: [
      { cn: "长江是中国最长的河流，全长约6300公里。",
        en: "The Yangtze River is the longest river in China, with a total length of about 6,300 kilometers.",
        note: "with + 名词短语，避免再加一个句子" },
      { cn: "长城是世界上最长的人造建筑，吸引了大量游客。",
        en: "The Great Wall is the longest man-made structure in the world, attracting a large number of tourists.",
        note: "attracting 现在分词作结果状语" },
      { cn: "杭州因西湖而闻名，每年接待数百万游客。",
        en: "Hangzhou is famous for the West Lake and receives millions of tourists every year.",
        note: "be famous for = 因…而闻名" },
      { cn: "这个国家由56个民族组成。",
        en: "The country consists of 56 ethnic groups.",
        note: "consist of = 由…组成，无被动语态" },
      { cn: "中国位于亚洲东部，面积约960万平方公里。",
        en: "China is located in the east of Asia, covering an area of about 9.6 million square kilometers.",
        note: "be located in + covering 分词短语" },
      { cn: "近年来，乡村旅游变得越来越受欢迎。",
        en: "In recent years, rural tourism has become increasingly popular.",
        note: "In recent years 通常配现在完成时" },
      { cn: "游客们被这里的美景深深吸引。",
        en: "The tourists were deeply attracted by the beautiful scenery here.",
        note: "被动语态 be attracted by" },
      { cn: "为了保护环境，当地政府限制了每日游客数量。",
        en: "In order to protect the environment, the local government has limited the number of visitors per day.",
        note: "In order to 表目的，放句首很清晰" },
    ],
  },
  {
    id: "education",
    name: "教育与社会",
    desc: "涉及学习方式、就业、科技。句式偏议论，注意连接词。",
    items: [
      { cn: "随着互联网的发展，在线学习变得越来越普遍。",
        en: "With the development of the Internet, online learning has become increasingly common.",
        note: "With + 名词短语，开头万能式" },
      { cn: "许多大学生通过做兼职来积累社会经验。",
        en: "Many college students accumulate social experience by taking part-time jobs.",
        note: "by doing 表方式" },
      { cn: "政府已经采取多项措施来改善教育条件。",
        en: "The government has taken a number of measures to improve educational conditions.",
        note: "take measures to do = 采取措施做某事" },
      { cn: "与过去相比，现在的大学生有更多出国留学的机会。",
        en: "Compared with the past, college students today have more opportunities to study abroad.",
        note: "Compared with 放句首作状语" },
      { cn: "阅读能力对学习任何语言都至关重要。",
        en: "Reading ability is of great importance to learning any language.",
        note: "be of great importance = be very important，更正式" },
      { cn: "越来越多的人意识到终身学习的重要性。",
        en: "More and more people are aware of the importance of lifelong learning.",
        note: "be aware of = 意识到" },
      { cn: "过度使用手机会影响学生的注意力。",
        en: "Excessive use of mobile phones may affect students' concentration.",
        note: "affect 是动词；effect 是名词，别写混" },
      { cn: "如果加以正确引导，网络可以成为有用的学习工具。",
        en: "If properly guided, the Internet can become a useful learning tool.",
        note: "If properly guided 是省略式状语从句（省略 it is）" },
    ],
  },
  {
    id: "food",
    name: "饮食与生活",
    desc: "常考饮食文化、健康、生活习惯。词汇偏生活化。",
    items: [
      { cn: "中国菜因口味丰富、做法多样而闻名世界。",
        en: "Chinese food is famous around the world for its rich flavors and various cooking methods.",
        note: "be famous for 的位置要放在状语前面或后面都行，别漏介词" },
      { cn: "米饭是南方人的主食，而北方人更喜欢吃面食。",
        en: "Rice is the staple food for people in the south, while those in the north prefer wheat-based food.",
        note: "while 表对比，是很好用的连接词" },
      { cn: "茶在中国已有几千年的历史。",
        en: "Tea has a history of several thousand years in China.",
        note: "have a history of + 时间" },
      { cn: "越来越多的人开始注重健康饮食。",
        en: "More and more people begin to pay attention to a healthy diet.",
        note: "pay attention to + 名词/动名词" },
      { cn: "早餐被认为是一天中最重要的一餐。",
        en: "Breakfast is considered to be the most important meal of the day.",
        note: "be considered to be = 被认为是" },
      { cn: "在家里做饭比在外面吃更健康也更便宜。",
        en: "Cooking at home is healthier and cheaper than eating out.",
        note: "动名词作主语，谓语用单数 is" },
      { cn: "不同地区的人们有着不同的饮食习惯。",
        en: "People in different regions have different eating habits.",
        note: "注意 people 是复数，不用加 s" },
      { cn: "减少糖的摄入有助于保持健康。",
        en: "Reducing sugar intake helps maintain good health.",
        note: "help (to) do，to 可以省略" },
    ],
  },
];

/* ===================== 对话：场景句型 ===================== */
const conversationScenarios = [
  {
    id: "campus", name: "校园生活", icon: "🎓",
    desc: "问课表、借笔记、找教室 —— 四级听力短对话的高频场景。",
    lines: [
      { en: "Excuse me, where is the lecture hall for Psychology 101?",
        cn: "打扰一下，心理学导论的讲堂在哪里？", tip: "问路用 Excuse me 开头最自然" },
      { en: "Could you tell me when the assignment is due?",
        cn: "你能告诉我作业什么时候交吗？", tip: "be due = 到期。听力里常听到 deadline 同义替换" },
      { en: "I'm afraid I missed the first part of the lecture. Could I borrow your notes?",
        cn: "我恐怕错过了讲座的前半部分。能借我看看你的笔记吗？", tip: "I'm afraid 用来软化语气，不是真的害怕" },
      { en: "Do you happen to know if the library is open on Sundays?",
        cn: "你知道图书馆周日开不开吗？", tip: "Do you happen to know 比 Do you know 更礼貌" },
      { en: "I'd like to sign up for the English corner. Is there a form to fill in?",
        cn: "我想报名英语角。有表格要填吗？", tip: "sign up for = 报名参加；fill in = 填写" },
      { en: "Sorry, I didn't catch that. Would you mind repeating it?",
        cn: "抱歉，我没听清。你介意再说一遍吗？", tip: "catch = 听清，非常地道的说法" },
      { en: "How long does it take to get from the dorm to the classroom building?",
        cn: "从宿舍到教学楼要多久？", tip: "How long does it take 是问时间的固定句式" },
      { en: "I'm thinking about dropping the course. It's harder than I expected.",
        cn: "我在考虑退掉这门课。它比我预想的难。", tip: "drop a course = 退课；be thinking about 表打算" },
    ],
  },
  {
    id: "restaurant", name: "点餐吃饭", icon: "🍽️",
    desc: "点单、买单、投诉 —— 听力里最常出现的生活场景之一。",
    lines: [
      { en: "A table for two, please. Could we sit by the window?",
        cn: "两位，谢谢。我们可以坐窗边吗？", tip: "A table for two 是进门第一句" },
      { en: "Could I see the menu, please?",
        cn: "可以给我看看菜单吗？", tip: "Could I ... 比 I want 礼貌得多" },
      { en: "I'll have the grilled chicken and a glass of orange juice.",
        cn: "我要烤鸡和一杯橙汁。", tip: "点菜用 I'll have，不用 I want" },
      { en: "Does this dish contain nuts? I'm allergic to them.",
        cn: "这道菜含坚果吗？我对坚果过敏。", tip: "be allergic to = 对…过敏" },
      { en: "Could we have the bill, please?",
        cn: "可以买单吗？", tip: "英式说 bill，美式说 check" },
      { en: "Excuse me, I think there's a mistake in the bill.",
        cn: "不好意思，我觉得账单有问题。", tip: "投诉时先 Excuse me + I think，比直接指责好" },
      { en: "Could you wrap this up for me? I'd like to take it away.",
        cn: "能帮我打包吗？我想带走。", tip: "wrap up = 打包；take away 英式，美式是 to go" },
      { en: "Keep the change. The food was great, by the way.",
        cn: "不用找零了。顺便说一句，菜很好吃。", tip: "Keep the change = 零钱留着" },
    ],
  },
  {
    id: "shopping", name: "购物", icon: "🛍️",
    desc: "问价、试穿、退换货。数字和尺寸是听力考点。",
    lines: [
      { en: "How much does this jacket cost?",
        cn: "这件夹克多少钱？", tip: "How much does ... cost 是最标准的问价" },
      { en: "Do you have this in a smaller size?",
        cn: "这件有小一号的吗？", tip: "in a smaller size = 小一号的" },
      { en: "Can I try it on?",
        cn: "我可以试穿吗？", tip: "try on 是试穿，代词要放中间：try it on" },
      { en: "Is there any discount on this?",
        cn: "这个有折扣吗？", tip: "discount on 后面接商品" },
      { en: "I'd like to return this. I bought the wrong size.",
        cn: "我想退掉这个。我买错尺寸了。", tip: "return = 退货；exchange = 换货" },
      { en: "Could I have a receipt, please?",
        cn: "可以给我一张收据吗？", tip: "receipt 里的 p 不发音：/rɪˈsiːt/" },
      { en: "That's a bit more than I wanted to spend.",
        cn: "这比我预想的贵了点。", tip: "委婉地说太贵，比 It's too expensive 得体" },
      { en: "I'll take it. Do you accept credit cards?",
        cn: "我买了。你们收信用卡吗？", tip: "I'll take it = 我买了" },
    ],
  },
  {
    id: "travel", name: "出行问路", icon: "🚌",
    desc: "坐车、订票、问路。方向和交通方式词汇是重点。",
    lines: [
      { en: "Excuse me, how do I get to the railway station?",
        cn: "打扰一下，请问火车站怎么走？", tip: "How do I get to ... 是最通用的问路句" },
      { en: "Is it within walking distance?",
        cn: "走路能到吗？", tip: "within walking distance = 步行可达" },
      { en: "Which line should I take to get to the museum?",
        cn: "去博物馆我该坐哪条线？", tip: "take a line = 坐某条线路" },
      { en: "How often does the bus run?",
        cn: "这趟公交多久一班？", tip: "How often 问频率，听力常考" },
      { en: "I'd like a round-trip ticket to Beijing, please.",
        cn: "我要一张去北京的往返票。", tip: "round-trip 往返 / one-way 单程" },
      { en: "Could you tell me when the next train leaves?",
        cn: "能告诉我下一班火车什么时候发车吗？", tip: "leave 表示（车）出发" },
      { en: "I think I'm lost. Am I going in the right direction?",
        cn: "我好像迷路了。我走的方向对吗？", tip: "go in the right direction = 方向对" },
      { en: "Go straight ahead and turn left at the second crossing.",
        cn: "一直往前走，在第二个路口左转。", tip: "go straight ahead / turn left / at the crossing，问路的经典回答" },
    ],
  },
  {
    id: "interview", name: "求职面试", icon: "💼",
    desc: "自我介绍、谈经历、问待遇。四级写作和听力都可能用到。",
    lines: [
      { en: "I'm a senior majoring in English at Nanjing University.",
        cn: "我是南京大学英语专业的大四学生。", tip: "major in = 主修；senior = 大四" },
      { en: "I have two years of experience working as a part-time translator.",
        cn: "我有两年兼职翻译的经验。", tip: "experience 作“经验”时不可数" },
      { en: "I'm good at working under pressure and meeting deadlines.",
        cn: "我擅长在压力下工作并按时完成任务。", tip: "meet a deadline = 按时完成" },
      { en: "Could you tell me more about the responsibilities of this position?",
        cn: "能再详细说说这个职位的职责吗？", tip: "面试中主动提问会加分" },
      { en: "Why do you think you are suitable for this job?",
        cn: "你为什么觉得自己适合这份工作？", tip: "be suitable for = 适合" },
      { en: "I would say my greatest strength is that I never give up easily.",
        cn: "我想我最大的优点是我不轻易放弃。", tip: "I would say 让回答不那么绝对" },
      { en: "May I ask about the salary and the working hours?",
        cn: "我可以问一下薪资和工作时间吗？", tip: "May I ask 比 I want to know 礼貌" },
      { en: "Thank you for the opportunity. I look forward to hearing from you.",
        cn: "感谢给我这个机会。期待您的回复。", tip: "面试结束的固定礼貌用语" },
    ],
  },
  {
    id: "doctor", name: "看病就医", icon: "🏥",
    desc: "描述症状、买药、预约。身体部位和症状词是考点。",
    lines: [
      { en: "I've had a sore throat and a headache for two days.",
        cn: "我喉咙痛、头疼两天了。", tip: "现在完成时 + for 表持续时间" },
      { en: "I don't feel well. I think I have a fever.",
        cn: "我不太舒服，我觉得我发烧了。", tip: "have a fever / a cold / a cough" },
      { en: "Do I need to make an appointment first?",
        cn: "我需要先预约吗？", tip: "make an appointment = 预约" },
      { en: "How often should I take this medicine?",
        cn: "这药我该多久吃一次？", tip: "How often 问频率；take medicine = 吃药" },
      { en: "I'm allergic to penicillin.",
        cn: "我对青霉素过敏。", tip: "看病时的重要信息，务必说清" },
      { en: "It hurts when I move my arm.",
        cn: "我一动胳膊就疼。", tip: "It hurts when ... 描述疼痛场景" },
      { en: "You should get more rest and drink plenty of water.",
        cn: "你应该多休息，多喝水。", tip: "医生常说的建议，听力里高频" },
      { en: "I'd like to book a check-up for next Monday.",
        cn: "我想预约下周一体检。", tip: "book = 预约（英式），check-up = 体检" },
    ],
  },
];
