// words-extra.js — 扩充词库（全局变量 vocabularyExtra）
// id 从 100 起：mock.js 已占用 1-70 且中间有空洞，从 100 起最清晰、便于以后继续追加。
// 每条含音标、释义、例句、例句译文、词根词缀记忆技巧。
// 说明：原项目随附的 PDF 词汇表文本层里没有中文（已逐页验证），无法提取，故这部分为手工编写。

const vocabularyExtra = [
  { id: 100, word: "balance", phonetic: "/ˈbæləns/", meaning: "n. 平衡；余额 v. 使平衡",
    example: "It is hard to balance study and rest.", exampleCN: "很难平衡学习和休息。",
    tip: "bi(二)+lance(盘) → 天平的两个盘子 → 平衡", list: "cet4-high", category: "high" },
  { id: 101, word: "ban", phonetic: "/bæn/", meaning: "v. 禁止 n. 禁令",
    example: "The school bans smoking on campus.", exampleCN: "学校禁止在校园内吸烟。",
    tip: "短词硬记：一纸禁令把门封上", list: "cet4-core", category: "high" },
  { id: 102, word: "bargain", phonetic: "/ˈbɑːɡɪn/", meaning: "n. 便宜货 v. 讨价还价",
    example: "This coat was a real bargain.", exampleCN: "这件外套真便宜。",
    tip: "bar(酒吧)+gain(获得) → 在酒吧谈成一笔好买卖", list: "cet4-core", category: "high" },
  { id: 103, word: "barrier", phonetic: "/ˈbæriə(r)/", meaning: "n. 障碍；屏障",
    example: "Language can be a barrier to communication.", exampleCN: "语言可能成为沟通的障碍。",
    tip: "bar(横杆)+rier → 拦路的横杆 → 障碍", list: "cet4-high", category: "high" },
  { id: 104, word: "basis", phonetic: "/ˈbeɪsɪs/", meaning: "n. 基础；根据",
    example: "Trust is the basis of friendship.", exampleCN: "信任是友谊的基础。",
    tip: "base(基础)+is → 基础（复数是 bases）", list: "cet4-high", category: "high" },
  { id: 105, word: "behave", phonetic: "/bɪˈheɪv/", meaning: "v. 表现；举止",
    example: "The children behaved well at the party.", exampleCN: "孩子们在聚会上表现很好。",
    tip: "be+have → 拥有自己的样子 → 举止", list: "cet4-core", category: "high" },
  { id: 106, word: "benefit", phonetic: "/ˈbenɪfɪt/", meaning: "n. 好处；利益 v. 有益于",
    example: "Exercise benefits your health.", exampleCN: "锻炼有益健康。",
    tip: "bene(好)+fit(做) → 做好事 → 好处", list: "cet4-high", category: "high" },
  { id: 107, word: "blame", phonetic: "/bleɪm/", meaning: "v. 责备 n. 责任",
    example: "Don't blame others for your mistakes.", exampleCN: "别把自己的错怪到别人头上。",
    tip: "形近 flame(火焰) → 火气上头就责备", list: "cet4-high", category: "high" },
  { id: 108, word: "bond", phonetic: "/bɒnd/", meaning: "n. 纽带；债券 v. 联结",
    example: "There is a strong bond between the sisters.", exampleCN: "姐妹之间有很强的纽带。",
    tip: "形近 band(带子) → 绑在一起的带子 → 纽带", list: "cet4-core", category: "high" },
  { id: 109, word: "boost", phonetic: "/buːst/", meaning: "v./n. 促进；提升",
    example: "Reading can boost your vocabulary.", exampleCN: "阅读能提升你的词汇量。",
    tip: "形近 boot(靴子) → 从后面踢一脚往上 → 提升", list: "cet4-high", category: "high" },
  { id: 110, word: "boundary", phonetic: "/ˈbaʊndri/", meaning: "n. 边界；界限",
    example: "The river forms the boundary between the two towns.", exampleCN: "这条河是两个镇的分界线。",
    tip: "bound(界限)+ary → 边界", list: "cet4-core", category: "high" },
  { id: 111, word: "brief", phonetic: "/briːf/", meaning: "adj. 简短的 v. 简要介绍",
    example: "He gave a brief introduction.", exampleCN: "他做了简短的介绍。",
    tip: "brev/brief 都表示“短”，如 abbreviate(缩写)", list: "cet4-high", category: "high" },
  { id: 112, word: "brilliant", phonetic: "/ˈbrɪliənt/", meaning: "adj. 杰出的；明亮的",
    example: "She came up with a brilliant idea.", exampleCN: "她想出了一个绝妙的主意。",
    tip: "brill(发光)+iant → 闪光的 → 杰出的", list: "cet4-core", category: "high" },
  { id: 113, word: "budget", phonetic: "/ˈbʌdʒɪt/", meaning: "n. 预算 v. 编预算",
    example: "We have a limited budget for the trip.", exampleCN: "我们这次旅行的预算有限。",
    tip: "联想 bag(袋子) → 袋子里的钱要规划 → 预算", list: "cet4-high", category: "high" },
  { id: 114, word: "burden", phonetic: "/ˈbɜːdn/", meaning: "n. 负担 v. 使负担",
    example: "He didn't want to be a burden to his family.", exampleCN: "他不想成为家人的负担。",
    tip: "形近 burn(烧) → 压得心里发烧 → 负担", list: "cet4-core", category: "high" },
  { id: 115, word: "calculate", phonetic: "/ˈkælkjuleɪt/", meaning: "v. 计算；估计",
    example: "Let me calculate the total cost.", exampleCN: "让我算一下总花费。",
    tip: "calcul(小石子)+ate → 古人用小石子计数", list: "cet4-high", category: "high" },
  { id: 116, word: "campaign", phonetic: "/kæmˈpeɪn/", meaning: "n. 运动；战役 v. 参加运动",
    example: "They started a campaign to save water.", exampleCN: "他们发起了节水运动。",
    tip: "camp(营地)+aign → 野外的大规模行动 → 战役/运动", list: "cet4-core", category: "high" },
  { id: 117, word: "campus", phonetic: "/ˈkæmpəs/", meaning: "n. 校园",
    example: "The campus is beautiful in autumn.", exampleCN: "秋天的校园很美。",
    tip: "camp(营地)+us → 我们的营地 → 校园", list: "cet4-high", category: "high" },
  { id: 118, word: "capable", phonetic: "/ˈkeɪpəbl/", meaning: "adj. 有能力的；能干的",
    example: "She is capable of solving the problem.", exampleCN: "她有能力解决这个问题。",
    tip: "cap(拿住)+able → 拿得住 → 有能力的", list: "cet4-high", category: "high" },
  { id: 119, word: "capacity", phonetic: "/kəˈpæsəti/", meaning: "n. 容量；能力",
    example: "The hall has a capacity of 500 people.", exampleCN: "这个大厅可容纳 500 人。",
    tip: "cap(容纳)+acity → 能装多少 → 容量", list: "cet4-high", category: "high" },
  { id: 120, word: "capital", phonetic: "/ˈkæpɪtl/", meaning: "n. 首都；资本 adj. 主要的",
    example: "Beijing is the capital of China.", exampleCN: "北京是中国的首都。",
    tip: "capit(头)+al → 头等重要的 → 首都/资本", list: "cet4-high", category: "high" },
  { id: 121, word: "career", phonetic: "/kəˈrɪə(r)/", meaning: "n. 职业；生涯",
    example: "She wants a career in medicine.", exampleCN: "她想从事医学方面的职业。",
    tip: "car(车)+eer → 人生的车道 → 生涯", list: "cet4-high", category: "high" },
  { id: 122, word: "category", phonetic: "/ˈkætəɡəri/", meaning: "n. 类别；范畴",
    example: "These books fall into three categories.", exampleCN: "这些书分成三类。",
    tip: "cata(向下)+gory → 归到某一类下面 → 类别", list: "cet4-core", category: "high" },
  { id: 123, word: "challenge", phonetic: "/ˈtʃælɪndʒ/", meaning: "n. 挑战 v. 向…挑战",
    example: "Learning a language is a challenge.", exampleCN: "学一门语言是个挑战。",
    tip: "联想 change → 逼你改变的东西 → 挑战", list: "cet4-high", category: "high" },
  { id: 124, word: "character", phonetic: "/ˈkærəktə(r)/", meaning: "n. 性格；角色；字符",
    example: "He has a strong character.", exampleCN: "他性格坚强。",
    tip: "charact(刻)+er → 刻在人身上的印记 → 性格", list: "cet4-high", category: "high" },
  { id: 125, word: "charge", phonetic: "/tʃɑːdʒ/", meaning: "v. 收费；充电；指控 n. 费用",
    example: "The hotel charges 200 yuan a night.", exampleCN: "这家旅馆一晚收费 200 元。",
    tip: "一词多义：收费 / 充电 / 指控，都含“装载”的意思", list: "cet4-high", category: "high" },
  { id: 126, word: "chemical", phonetic: "/ˈkemɪkl/", meaning: "adj. 化学的 n. 化学品",
    example: "This chemical is harmful to skin.", exampleCN: "这种化学品对皮肤有害。",
    tip: "chem(化学)+ical → 化学的", list: "cet4-core", category: "high" },
  { id: 127, word: "circumstance", phonetic: "/ˈsɜːkəmstəns/", meaning: "n. 情况；环境",
    example: "Under no circumstances should you give up.", exampleCN: "任何情况下你都不该放弃。",
    tip: "circum(周围)+stance(站) → 周围的站位 → 环境", list: "cet4-core", category: "high" },
  { id: 128, word: "civil", phonetic: "/ˈsɪvl/", meaning: "adj. 公民的；文明的",
    example: "We should protect civil rights.", exampleCN: "我们应该保护公民权利。",
    tip: "civ(公民)+il → 公民的", list: "cet4-core", category: "high" },
  { id: 129, word: "claim", phonetic: "/kleɪm/", meaning: "v. 声称；索赔 n. 主张",
    example: "He claims that he saw the accident.", exampleCN: "他声称看到了那起事故。",
    tip: "形近 clap(拍手) → 拍着胸口大声说 → 声称", list: "cet4-high", category: "high" },
  { id: 130, word: "classic", phonetic: "/ˈklæsɪk/", meaning: "adj. 经典的 n. 经典作品",
    example: "This song is a classic.", exampleCN: "这首歌是经典。",
    tip: "class(等级)+ic → 顶级档次的 → 经典", list: "cet4-core", category: "high" },
  { id: 131, word: "client", phonetic: "/ˈklaɪənt/", meaning: "n. 客户；委托人",
    example: "The company lost an important client.", exampleCN: "公司失去了一个重要客户。",
    tip: "cli(倾斜)+ent → 依赖你的一方 → 客户", list: "cet4-core", category: "high" },
  { id: 132, word: "climate", phonetic: "/ˈklaɪmət/", meaning: "n. 气候；风气",
    example: "The climate here is mild.", exampleCN: "这里气候温和。",
    tip: "clim(倾斜)+ate → 地球倾斜决定气候带", list: "cet4-high", category: "high" },
  { id: 133, word: "combine", phonetic: "/kəmˈbaɪn/", meaning: "v. 结合；联合",
    example: "Combine study with exercise.", exampleCN: "把学习和锻炼结合起来。",
    tip: "com(共同)+bine(二) → 合二为一", list: "cet4-high", category: "high" },
  { id: 134, word: "comment", phonetic: "/ˈkɒment/", meaning: "n. 评论 v. 评论",
    example: "He made no comment on the plan.", exampleCN: "他对这个计划没作评论。",
    tip: "com(共同)+ment(想法) → 把想法说出来 → 评论", list: "cet4-high", category: "high" },
  { id: 135, word: "commit", phonetic: "/kəˈmɪt/", meaning: "v. 犯（错）；承诺；投入",
    example: "He committed a serious mistake.", exampleCN: "他犯了一个严重错误。",
    tip: "com(共同)+mit(送) → 把自己交出去 → 承诺/犯错", list: "cet4-high", category: "high" },
  { id: 136, word: "committee", phonetic: "/kəˈmɪti/", meaning: "n. 委员会",
    example: "The committee will meet next week.", exampleCN: "委员会下周开会。",
    tip: "commit(委派)+tee → 被委派的一群人 → 委员会", list: "cet4-core", category: "high" },
  { id: 137, word: "communicate", phonetic: "/kəˈmjuːnɪkeɪt/", meaning: "v. 交流；传达",
    example: "We communicate by email.", exampleCN: "我们通过电子邮件交流。",
    tip: "commun(共同)+icate → 使共有 → 交流", list: "cet4-high", category: "high" },
  { id: 138, word: "community", phonetic: "/kəˈmjuːnəti/", meaning: "n. 社区；群体",
    example: "She is active in the local community.", exampleCN: "她在当地社区很活跃。",
    tip: "commun(共同)+ity → 共同生活的一群人", list: "cet4-high", category: "high" },
  { id: 139, word: "compare", phonetic: "/kəmˈpeə(r)/", meaning: "v. 比较；对比",
    example: "Compare the two answers carefully.", exampleCN: "仔细比较这两个答案。",
    tip: "com(共同)+pare(相等) → 放在一起看是否相等", list: "cet4-high", category: "high" },
  { id: 140, word: "compete", phonetic: "/kəmˈpiːt/", meaning: "v. 竞争；比赛",
    example: "Many students compete for the scholarship.", exampleCN: "许多学生竞争这笔奖学金。",
    tip: "com(共同)+pete(追求) → 共同追求同一目标 → 竞争", list: "cet4-high", category: "high" },
  { id: 141, word: "complain", phonetic: "/kəmˈpleɪn/", meaning: "v. 抱怨；投诉",
    example: "He always complains about the food.", exampleCN: "他总是抱怨食物。",
    tip: "com(加强)+plain(捶胸) → 捶着胸口诉苦 → 抱怨", list: "cet4-high", category: "high" },
  { id: 142, word: "complex", phonetic: "/ˈkɒmpleks/", meaning: "adj. 复杂的 n. 综合体",
    example: "This is a complex problem.", exampleCN: "这是个复杂的问题。",
    tip: "com(共同)+plex(折叠) → 多层折叠在一起 → 复杂", list: "cet4-high", category: "high" },
  { id: 143, word: "concentrate", phonetic: "/ˈkɒnsntreɪt/", meaning: "v. 集中；专心",
    example: "I can't concentrate in a noisy room.", exampleCN: "在吵闹的房间里我无法专心。",
    tip: "con(共同)+centr(中心)+ate → 聚到中心 → 集中", list: "cet4-high", category: "high" },
  { id: 144, word: "concept", phonetic: "/ˈkɒnsept/", meaning: "n. 概念；观念",
    example: "The concept is easy to understand.", exampleCN: "这个概念很容易理解。",
    tip: "con(共同)+cept(拿) → 共同把握的东西 → 概念", list: "cet4-core", category: "high" },
  { id: 145, word: "concern", phonetic: "/kənˈsɜːn/", meaning: "n. 关心；担忧 v. 涉及",
    example: "Her health is my biggest concern.", exampleCN: "她的健康是我最担心的事。",
    tip: "con(共同)+cern(筛) → 一起筛一遍 → 关心", list: "cet4-high", category: "high" },
  { id: 146, word: "conclude", phonetic: "/kənˈkluːd/", meaning: "v. 得出结论；结束",
    example: "We concluded that he was right.", exampleCN: "我们得出结论：他是对的。",
    tip: "con(共同)+clude(关闭) → 一起关上 → 结束/下结论", list: "cet4-high", category: "high" },
  { id: 147, word: "condition", phonetic: "/kənˈdɪʃn/", meaning: "n. 条件；状况",
    example: "The car is in good condition.", exampleCN: "这辆车的状况良好。",
    tip: "con(共同)+dit(说)+ion → 共同商定的 → 条件", list: "cet4-high", category: "high" },
  { id: 148, word: "conduct", phonetic: "/kənˈdʌkt/", meaning: "v. 进行；指挥 n. 行为",
    example: "They conducted a survey among students.", exampleCN: "他们在学生中进行了一项调查。",
    tip: "con(共同)+duct(引导) → 引导着进行", list: "cet4-core", category: "high" },
  { id: 149, word: "confidence", phonetic: "/ˈkɒnfɪdəns/", meaning: "n. 信心；信任",
    example: "Practice gives you confidence.", exampleCN: "练习会给你信心。",
    tip: "con(加强)+fid(信任)+ence → 充分地信任 → 信心", list: "cet4-high", category: "high" },
  { id: 150, word: "confirm", phonetic: "/kənˈfɜːm/", meaning: "v. 确认；证实",
    example: "Please confirm your booking.", exampleCN: "请确认你的预订。",
    tip: "con(加强)+firm(坚固) → 使坚固 → 确认", list: "cet4-core", category: "high" },
  { id: 151, word: "conflict", phonetic: "/ˈkɒnflɪkt/", meaning: "n. 冲突 v. 冲突；抵触",
    example: "There is a conflict between the two plans.", exampleCN: "这两个计划之间有冲突。",
    tip: "con(共同)+flict(打) → 互相对打 → 冲突", list: "cet4-high", category: "high" },
  { id: 152, word: "confuse", phonetic: "/kənˈfjuːz/", meaning: "v. 使困惑；混淆",
    example: "The instructions confused me.", exampleCN: "那些说明把我弄糊涂了。",
    tip: "con(共同)+fuse(倒) → 全倒在一起 → 混乱", list: "cet4-high", category: "high" },
  { id: 153, word: "consequence", phonetic: "/ˈkɒnsɪkwəns/", meaning: "n. 后果；结果",
    example: "Think about the consequences first.", exampleCN: "先想想后果。",
    tip: "con(共同)+sequ(跟随)+ence → 跟着来的东西 → 后果", list: "cet4-high", category: "high" },
  { id: 154, word: "conservative", phonetic: "/kənˈsɜːvətɪv/", meaning: "adj. 保守的 n. 保守派",
    example: "He has conservative views.", exampleCN: "他的观点比较保守。",
    tip: "conserve(保存)+ative → 想保存旧的 → 保守", list: "cet4-core", category: "high" },
  { id: 155, word: "considerable", phonetic: "/kənˈsɪdərəbl/", meaning: "adj. 相当大的；可观的",
    example: "It took a considerable amount of time.", exampleCN: "花了相当多的时间。",
    tip: "consider(考虑)+able → 值得认真考虑的量 → 可观的", list: "cet4-core", category: "high" },
  { id: 156, word: "consist", phonetic: "/kənˈsɪst/", meaning: "v. 由…组成；在于",
    example: "The team consists of five members.", exampleCN: "这个团队由五名成员组成。",
    tip: "con(共同)+sist(站) → 站在一起 → 组成", list: "cet4-high", category: "high" },
  { id: 157, word: "constant", phonetic: "/ˈkɒnstənt/", meaning: "adj. 持续的；不变的",
    example: "She lives in constant fear.", exampleCN: "她一直生活在恐惧中。",
    tip: "con(加强)+stant(站) → 一直站着不动 → 不变", list: "cet4-high", category: "high" },
  { id: 158, word: "construct", phonetic: "/kənˈstrʌkt/", meaning: "v. 建造；构建",
    example: "They constructed a new bridge.", exampleCN: "他们建了一座新桥。",
    tip: "con(共同)+struct(建) → 一起建造", list: "cet4-high", category: "high" },
  { id: 159, word: "consume", phonetic: "/kənˈsjuːm/", meaning: "v. 消耗；消费",
    example: "This car consumes a lot of fuel.", exampleCN: "这辆车很耗油。",
    tip: "con(加强)+sume(拿) → 全拿走 → 消耗", list: "cet4-high", category: "high" },
  { id: 160, word: "contain", phonetic: "/kənˈteɪn/", meaning: "v. 包含；容纳",
    example: "The box contains old photos.", exampleCN: "盒子里装着旧照片。",
    tip: "con(共同)+tain(握) → 一起握住 → 包含", list: "cet4-high", category: "high" },
  { id: 161, word: "contemporary", phonetic: "/kənˈtemprəri/", meaning: "adj. 当代的；同时代的",
    example: "She studies contemporary art.", exampleCN: "她研究当代艺术。",
    tip: "con(共同)+tempor(时间)+ary → 同一时间的 → 当代", list: "cet4-core", category: "high" },
  { id: 162, word: "content", phonetic: "/ˈkɒntent/", meaning: "n. 内容 adj. 满足的",
    example: "The content of the book is useful.", exampleCN: "这本书的内容很实用。",
    tip: "con(共同)+tent(握) → 里面装的东西 → 内容", list: "cet4-high", category: "high" },
  { id: 163, word: "context", phonetic: "/ˈkɒntekst/", meaning: "n. 上下文；背景",
    example: "Guess the word from the context.", exampleCN: "从上下文猜这个词的意思。",
    tip: "con(共同)+text(编织) → 一起编织起来 → 上下文", list: "cet4-core", category: "high" },
  { id: 164, word: "contract", phonetic: "/ˈkɒntrækt/", meaning: "n. 合同 v. 收缩；订约",
    example: "They signed a two-year contract.", exampleCN: "他们签了一份两年合同。",
    tip: "con(共同)+tract(拉) → 拉到一起 → 合同/收缩", list: "cet4-high", category: "high" },
  { id: 165, word: "contrast", phonetic: "/ˈkɒntrɑːst/", meaning: "n. 对比 v. 形成对比",
    example: "There is a sharp contrast between the two.", exampleCN: "两者形成鲜明对比。",
    tip: "contra(相反)+st(站) → 站在对立面 → 对比", list: "cet4-high", category: "high" },
  { id: 166, word: "contribute", phonetic: "/kənˈtrɪbjuːt/", meaning: "v. 贡献；促成",
    example: "Everyone contributed to the success.", exampleCN: "每个人都为成功做出了贡献。",
    tip: "con(共同)+tribute(给予) → 一起给 → 贡献", list: "cet4-high", category: "high" },
  { id: 167, word: "convenient", phonetic: "/kənˈviːniənt/", meaning: "adj. 方便的；便利的",
    example: "Is Monday convenient for you?", exampleCN: "周一你方便吗？",
    tip: "con(共同)+ven(来)+ient → 能凑到一起 → 方便", list: "cet4-high", category: "high" },
  { id: 168, word: "convince", phonetic: "/kənˈvɪns/", meaning: "v. 使信服；说服",
    example: "He convinced me to join the club.", exampleCN: "他说服我加入了社团。",
    tip: "con(加强)+vince(征服) → 征服对方的想法 → 说服", list: "cet4-high", category: "high" },
  { id: 169, word: "cooperate", phonetic: "/kəʊˈɒpəreɪt/", meaning: "v. 合作；配合",
    example: "The two teams cooperated well.", exampleCN: "两个队合作得很好。",
    tip: "co(共同)+oper(工作)+ate → 一起工作 → 合作", list: "cet4-core", category: "high" },
  { id: 170, word: "core", phonetic: "/kɔː(r)/", meaning: "n. 核心；果核",
    example: "This is the core of the problem.", exampleCN: "这是问题的核心。",
    tip: "形近 corn(玉米) → 玉米芯 → 核心", list: "cet4-high", category: "high" },
  { id: 171, word: "courage", phonetic: "/ˈkʌrɪdʒ/", meaning: "n. 勇气；胆量",
    example: "It takes courage to say no.", exampleCN: "说“不”是需要勇气的。",
    tip: "cour(心)+age → 心的力量 → 勇气", list: "cet4-high", category: "high" },
  { id: 172, word: "credit", phonetic: "/ˈkredɪt/", meaning: "n. 信用；学分 v. 归功于",
    example: "You need 20 credits to graduate.", exampleCN: "毕业需要 20 个学分。",
    tip: "cred(相信)+it → 被相信 → 信用", list: "cet4-high", category: "high" },
  { id: 173, word: "crisis", phonetic: "/ˈkraɪsɪs/", meaning: "n. 危机；紧要关头",
    example: "The country faced an economic crisis.", exampleCN: "这个国家面临经济危机。",
    tip: "cri(判断)+sis → 必须作出决断的时刻 → 危机", list: "cet4-high", category: "high" },
  { id: 174, word: "criticize", phonetic: "/ˈkrɪtɪsaɪz/", meaning: "v. 批评；评论",
    example: "Don't criticize others too quickly.", exampleCN: "别急着批评别人。",
    tip: "critic(评判)+ize → 作出评判 → 批评", list: "cet4-core", category: "high" },
  { id: 175, word: "crucial", phonetic: "/ˈkruːʃl/", meaning: "adj. 至关重要的；决定性的",
    example: "Sleep is crucial for memory.", exampleCN: "睡眠对记忆至关重要。",
    tip: "cruc(十字)+ial → 十字路口要做决定 → 关键的", list: "cet4-core", category: "high" },
  { id: 176, word: "cultivate", phonetic: "/ˈkʌltɪveɪt/", meaning: "v. 培养；耕作",
    example: "Cultivate the habit of reading.", exampleCN: "培养阅读的习惯。",
    tip: "cult(耕作)+ivate → 耕作 → 培养", list: "cet4-core", category: "high" },
  { id: 177, word: "current", phonetic: "/ˈkʌrənt/", meaning: "adj. 当前的 n. 水流；电流",
    example: "What is the current situation?", exampleCN: "目前的情况怎么样？",
    tip: "curr(跑)+ent → 正在跑的 → 当前", list: "cet4-high", category: "high" },
  { id: 178, word: "damage", phonetic: "/ˈdæmɪdʒ/", meaning: "n./v. 损害；破坏",
    example: "The storm damaged many houses.", exampleCN: "风暴损坏了许多房屋。",
    tip: "dam(损失)+age → 造成损失 → 损害", list: "cet4-high", category: "high" },
  { id: 179, word: "data", phonetic: "/ˈdeɪtə/", meaning: "n. 数据；资料",
    example: "The data shows a clear trend.", exampleCN: "数据显示出明显的趋势。",
    tip: "dat(给)+a → 给出的东西 → 资料（复数名词）", list: "cet4-high", category: "high" },
  { id: 180, word: "deadline", phonetic: "/ˈdedlaɪn/", meaning: "n. 截止日期；最后期限",
    example: "The deadline is next Friday.", exampleCN: "截止日期是下周五。",
    tip: "dead(死)+line(线) → 越过就死的线 → 截止", list: "cet4-core", category: "high" },
  { id: 181, word: "debate", phonetic: "/dɪˈbeɪt/", meaning: "n./v. 辩论；争论",
    example: "They debated the topic for an hour.", exampleCN: "他们就这个话题辩论了一小时。",
    tip: "de(加强)+bate(打) → 用嘴打 → 辩论", list: "cet4-high", category: "high" },
  { id: 182, word: "decade", phonetic: "/ˈdekeɪd/", meaning: "n. 十年",
    example: "He worked there for a decade.", exampleCN: "他在那里工作了十年。",
    tip: "dec(十)+ade → 十年", list: "cet4-high", category: "high" },
  { id: 183, word: "decline", phonetic: "/dɪˈklaɪn/", meaning: "v./n. 下降；拒绝",
    example: "Sales declined last year.", exampleCN: "去年销量下降了。",
    tip: "de(向下)+cline(倾斜) → 向下倾 → 下降/谢绝", list: "cet4-high", category: "high" },
  { id: 184, word: "defeat", phonetic: "/dɪˈfiːt/", meaning: "v. 击败 n. 失败",
    example: "Our team defeated theirs.", exampleCN: "我们队击败了他们队。",
    tip: "de(解除)+feat(做) → 使对方做不成 → 击败", list: "cet4-core", category: "high" },
  { id: 185, word: "defend", phonetic: "/dɪˈfend/", meaning: "v. 保卫；辩护",
    example: "We must defend our rights.", exampleCN: "我们必须捍卫自己的权利。",
    tip: "de(解除)+fend(打) → 打退 → 保卫", list: "cet4-high", category: "high" },
  { id: 186, word: "define", phonetic: "/dɪˈfaɪn/", meaning: "v. 定义；阐明",
    example: "Please define this term.", exampleCN: "请给这个术语下定义。",
    tip: "de(加强)+fine(界限) → 划出界限 → 定义", list: "cet4-high", category: "high" },
  { id: 187, word: "delay", phonetic: "/dɪˈleɪ/", meaning: "v./n. 延迟；耽误",
    example: "The flight was delayed by two hours.", exampleCN: "航班延误了两个小时。",
    tip: "de(离开)+lay(放) → 放到一边 → 延误", list: "cet4-high", category: "high" },
  { id: 188, word: "deliver", phonetic: "/dɪˈlɪvə(r)/", meaning: "v. 递送；发表；接生",
    example: "He delivered a great speech.", exampleCN: "他发表了一场精彩的演讲。",
    tip: "de(加强)+liver(自由) → 使东西脱手 → 送出", list: "cet4-high", category: "high" },
  { id: 189, word: "demand", phonetic: "/dɪˈmɑːnd/", meaning: "n. 需求；要求 v. 要求",
    example: "There is a high demand for teachers.", exampleCN: "教师的需求量很大。",
    tip: "de(加强)+mand(命令) → 强烈要求 → 需求", list: "cet4-high", category: "high" },
  { id: 190, word: "demonstrate", phonetic: "/ˈdemənstreɪt/", meaning: "v. 证明；演示；示威",
    example: "Let me demonstrate how it works.", exampleCN: "让我演示一下它怎么用。",
    tip: "de(完全)+monstr(展示)+ate → 完整展示 → 演示", list: "cet4-core", category: "high" },
  { id: 191, word: "deny", phonetic: "/dɪˈnaɪ/", meaning: "v. 否认；拒绝给予",
    example: "He denied taking the money.", exampleCN: "他否认拿了那笔钱。",
    tip: "de(加强)+ny(否) → 一口否认", list: "cet4-high", category: "high" },
  { id: 192, word: "depend", phonetic: "/dɪˈpend/", meaning: "v. 依赖；取决于",
    example: "Children depend on their parents.", exampleCN: "孩子依赖父母。",
    tip: "de(向下)+pend(挂) → 挂在下面 → 依赖", list: "cet4-high", category: "high" },
  { id: 193, word: "depress", phonetic: "/dɪˈpres/", meaning: "v. 使沮丧；使萧条",
    example: "The bad news depressed everyone.", exampleCN: "坏消息让每个人都沮丧。",
    tip: "de(向下)+press(压) → 压下去 → 沮丧", list: "cet4-core", category: "high" },
  { id: 194, word: "derive", phonetic: "/dɪˈraɪv/", meaning: "v. 得到；源自",
    example: "She derives pleasure from music.", exampleCN: "她从音乐中获得快乐。",
    tip: "de(从)+rive(河) → 从河里引水 → 源自", list: "cet4-core", category: "high" },
  { id: 195, word: "describe", phonetic: "/dɪˈskraɪb/", meaning: "v. 描述；形容",
    example: "Can you describe the man you saw?", exampleCN: "你能描述一下你看到的那个人吗？",
    tip: "de(向下)+scribe(写) → 写下来 → 描述", list: "cet4-high", category: "high" },
  { id: 196, word: "deserve", phonetic: "/dɪˈzɜːv/", meaning: "v. 值得；应得",
    example: "You deserve a good rest.", exampleCN: "你该好好休息一下。",
    tip: "de(加强)+serve(服务) → 服务到位 → 应得", list: "cet4-high", category: "high" },
  { id: 197, word: "desire", phonetic: "/dɪˈzaɪə(r)/", meaning: "n./v. 渴望；愿望",
    example: "He has a strong desire to learn.", exampleCN: "他有强烈的学习渴望。",
    tip: "de(加强)+sire(渴望) → 强烈渴望", list: "cet4-high", category: "high" },
  { id: 198, word: "despite", phonetic: "/dɪˈspaɪt/", meaning: "prep. 尽管；不管",
    example: "Despite the rain, we went out.", exampleCN: "尽管下雨，我们还是出门了。",
    tip: "de(向下)+spite(看) → 不往下看 → 不顾 → 尽管", list: "cet4-high", category: "high" },
  { id: 199, word: "destroy", phonetic: "/dɪˈstrɔɪ/", meaning: "v. 摧毁；破坏",
    example: "The fire destroyed the building.", exampleCN: "大火摧毁了那栋建筑。",
    tip: "de(向下)+stroy(建) → 把建的拆掉 → 摧毁", list: "cet4-high", category: "high" },
  { id: 200, word: "detail", phonetic: "/ˈdiːteɪl/", meaning: "n. 细节 v. 详述",
    example: "Tell me every detail.", exampleCN: "把每个细节都告诉我。",
    tip: "de(加强)+tail(切) → 切得很细 → 细节", list: "cet4-high", category: "high" },
  { id: 201, word: "detect", phonetic: "/dɪˈtekt/", meaning: "v. 察觉；侦查",
    example: "I detected a change in his voice.", exampleCN: "我察觉到他声音的变化。",
    tip: "de(去掉)+tect(盖) → 揭开盖子 → 察觉", list: "cet4-core", category: "high" },
  { id: 202, word: "determine", phonetic: "/dɪˈtɜːmɪn/", meaning: "v. 决定；确定",
    example: "Attitude determines success.", exampleCN: "态度决定成功。",
    tip: "de(加强)+termine(界限) → 定下界限 → 决定", list: "cet4-high", category: "high" },
  { id: 203, word: "develop", phonetic: "/dɪˈveləp/", meaning: "v. 发展；开发；培养",
    example: "Reading develops the mind.", exampleCN: "阅读能开发心智。",
    tip: "de(解除)+velop(包裹) → 解开包裹 → 发展", list: "cet4-high", category: "high" },
  { id: 204, word: "device", phonetic: "/dɪˈvaɪs/", meaning: "n. 装置；设备；手段",
    example: "This device saves energy.", exampleCN: "这个装置很省电。",
    tip: "de(分开)+vice(分) → 分开做出来的东西 → 装置", list: "cet4-high", category: "high" },
  { id: 205, word: "devote", phonetic: "/dɪˈvəʊt/", meaning: "v. 奉献；致力于",
    example: "She devoted her life to teaching.", exampleCN: "她把一生献给了教学。",
    tip: "de(加强)+vote(誓言) → 立誓去做 → 奉献", list: "cet4-high", category: "high" },
  { id: 206, word: "differ", phonetic: "/ˈdɪfə(r)/", meaning: "v. 不同；相异",
    example: "Opinions differ on this issue.", exampleCN: "在这个问题上意见不一。",
    tip: "dif(分开)+fer(带) → 分开带走 → 不同", list: "cet4-core", category: "high" },
  { id: 207, word: "digital", phonetic: "/ˈdɪdʒɪtl/", meaning: "adj. 数字的；数码的",
    example: "We live in a digital age.", exampleCN: "我们生活在数字时代。",
    tip: "digit(手指/数字)+al → 用手指计数的 → 数字的", list: "cet4-high", category: "high" },
  { id: 208, word: "discipline", phonetic: "/ˈdɪsəplɪn/", meaning: "n. 纪律；学科 v. 训练",
    example: "Good discipline helps you study.", exampleCN: "良好的纪律有助于学习。",
    tip: "disc(学习)+ipline → 学习者要守的规矩 → 纪律", list: "cet4-core", category: "high" },
  { id: 209, word: "discount", phonetic: "/ˈdɪskaʊnt/", meaning: "n. 折扣 v. 打折",
    example: "Students get a 20% discount.", exampleCN: "学生可以打八折。",
    tip: "dis(去掉)+count(计数) → 少算一部分 → 折扣", list: "cet4-high", category: "high" },
  { id: 210, word: "display", phonetic: "/dɪˈspleɪ/", meaning: "v./n. 展示；陈列",
    example: "The museum displays ancient tools.", exampleCN: "博物馆展出古代工具。",
    tip: "dis(分开)+play(折) → 展开给人看 → 展示", list: "cet4-high", category: "high" },
  { id: 211, word: "dispute", phonetic: "/dɪˈspjuːt/", meaning: "n./v. 争论；纠纷",
    example: "They are in a dispute over money.", exampleCN: "他们正为钱争执。",
    tip: "dis(分开)+pute(想) → 想法分开 → 争执", list: "cet4-core", category: "high" },
  { id: 212, word: "distinguish", phonetic: "/dɪˈstɪŋɡwɪʃ/", meaning: "v. 区分；辨别",
    example: "Can you distinguish the two sounds?", exampleCN: "你能区分这两个音吗？",
    tip: "di(分开)+stingu(刺)+ish → 刺出区别 → 区分", list: "cet4-high", category: "high" },
  { id: 213, word: "distribute", phonetic: "/dɪˈstrɪbjuːt/", meaning: "v. 分发；分配",
    example: "They distributed food to the poor.", exampleCN: "他们给穷人分发食物。",
    tip: "dis(分开)+tribute(给) → 分开给 → 分发", list: "cet4-core", category: "high" },
  { id: 214, word: "disturb", phonetic: "/dɪˈstɜːb/", meaning: "v. 打扰；扰乱",
    example: "Don't disturb him while he studies.", exampleCN: "他学习时别打扰他。",
    tip: "dis(加强)+turb(搅动) → 搅乱 → 打扰", list: "cet4-high", category: "high" },
  { id: 215, word: "diverse", phonetic: "/daɪˈvɜːs/", meaning: "adj. 多样的；不同的",
    example: "The city has a diverse culture.", exampleCN: "这座城市文化多元。",
    tip: "di(分开)+verse(转) → 转向各处 → 多样", list: "cet4-core", category: "high" },
  { id: 216, word: "document", phonetic: "/ˈdɒkjumənt/", meaning: "n. 文件 v. 记录",
    example: "Please sign this document.", exampleCN: "请在这份文件上签字。",
    tip: "doc(教)+ument → 用来告知的东西 → 文件", list: "cet4-high", category: "high" },
  { id: 217, word: "domestic", phonetic: "/dəˈmestɪk/", meaning: "adj. 国内的；家庭的",
    example: "Domestic travel is cheaper.", exampleCN: "国内旅行更便宜。",
    tip: "dom(家)+estic → 家里的 → 国内的", list: "cet4-high", category: "high" },
  { id: 218, word: "dominate", phonetic: "/ˈdɒmɪneɪt/", meaning: "v. 支配；主导",
    example: "One team dominated the game.", exampleCN: "一支队伍主导了整场比赛。",
    tip: "domin(主人)+ate → 当主人 → 支配", list: "cet4-core", category: "high" },
  { id: 219, word: "doubt", phonetic: "/daʊt/", meaning: "n./v. 怀疑；疑问",
    example: "I doubt that he will come.", exampleCN: "我怀疑他不会来。",
    tip: "b 不发音：/daʊt/，联想“心里打鼓” → 怀疑", list: "cet4-high", category: "high" },
  { id: 220, word: "draft", phonetic: "/drɑːft/", meaning: "n. 草稿 v. 起草",
    example: "Write a draft first.", exampleCN: "先写个草稿。",
    tip: "形近 draw(画) → 先画个轮廓 → 草稿", list: "cet4-core", category: "high" },
  { id: 221, word: "dramatic", phonetic: "/drəˈmætɪk/", meaning: "adj. 戏剧性的；显著的",
    example: "There was a dramatic change.", exampleCN: "发生了显著的变化。",
    tip: "drama(戏剧)+tic → 像戏一样 → 戏剧性的", list: "cet4-core", category: "high" },
  { id: 222, word: "duration", phonetic: "/djuˈreɪʃn/", meaning: "n. 持续时间；期间",
    example: "The duration of the course is 3 months.", exampleCN: "这门课为期三个月。",
    tip: "dur(持久)+ation → 持续多久 → 期间", list: "cet4-core", category: "high" },
  { id: 223, word: "eager", phonetic: "/ˈiːɡə(r)/", meaning: "adj. 渴望的；热切的",
    example: "She is eager to learn.", exampleCN: "她渴望学习。",
    tip: "形近 eagle(鹰) → 鹰一样急切地盯着 → 渴望", list: "cet4-high", category: "high" },
  { id: 224, word: "earn", phonetic: "/ɜːn/", meaning: "v. 赚得；赢得",
    example: "He earns 5000 yuan a month.", exampleCN: "他每月挣五千元。",
    tip: "形近 learn → 学了本事才能赚", list: "cet4-high", category: "high" },
  { id: 225, word: "efficient", phonetic: "/ɪˈfɪʃnt/", meaning: "adj. 高效的；效率高的",
    example: "This is a more efficient method.", exampleCN: "这是更高效的方法。",
    tip: "ef(出)+fic(做)+ient → 能做出成果 → 高效", list: "cet4-high", category: "high" },
  { id: 226, word: "eliminate", phonetic: "/ɪˈlɪmɪneɪt/", meaning: "v. 消除；淘汰",
    example: "We must eliminate the error.", exampleCN: "我们必须消除这个错误。",
    tip: "e(出)+limin(门槛)+ate → 赶出门 → 消除", list: "cet4-core", category: "high" },
  { id: 227, word: "emerge", phonetic: "/ɪˈmɜːdʒ/", meaning: "v. 出现；浮现",
    example: "The sun emerged from the clouds.", exampleCN: "太阳从云层中露出来。",
    tip: "e(出)+merge(沉) → 从沉没中出来 → 浮现", list: "cet4-high", category: "high" },
  { id: 228, word: "emphasize", phonetic: "/ˈemfəsaɪz/", meaning: "v. 强调；着重",
    example: "He emphasized the importance of practice.", exampleCN: "他强调了练习的重要性。",
    tip: "em(使)+phase(阶段)+ize → 使凸显出来 → 强调", list: "cet4-high", category: "high" },
  { id: 229, word: "employ", phonetic: "/ɪmˈplɔɪ/", meaning: "v. 雇用；使用",
    example: "The factory employs 200 workers.", exampleCN: "这家工厂雇用了 200 名工人。",
    tip: "em(使)+ploy(用) → 使用 → 雇用", list: "cet4-high", category: "high" },
  { id: 230, word: "encourage", phonetic: "/ɪnˈkʌrɪdʒ/", meaning: "v. 鼓励；促进",
    example: "My teacher encouraged me to try.", exampleCN: "老师鼓励我去尝试。",
    tip: "en(使)+courage(勇气) → 给你勇气 → 鼓励", list: "cet4-high", category: "high" },
  { id: 231, word: "enormous", phonetic: "/ɪˈnɔːməs/", meaning: "adj. 巨大的；庞大的",
    example: "The cost was enormous.", exampleCN: "成本非常巨大。",
    tip: "e(出)+norm(标准)+ous → 超出标准 → 巨大", list: "cet4-high", category: "high" },
  { id: 232, word: "ensure", phonetic: "/ɪnˈʃʊə(r)/", meaning: "v. 确保；保证",
    example: "Please ensure the door is locked.", exampleCN: "请确保门锁好了。",
    tip: "en(使)+sure(确定) → 使确定 → 确保", list: "cet4-high", category: "high" },
  { id: 233, word: "enthusiasm", phonetic: "/ɪnˈθjuːziæzəm/", meaning: "n. 热情；热心",
    example: "She shows great enthusiasm for music.", exampleCN: "她对音乐表现出极大的热情。",
    tip: "en(在…之中)+thus(神)+iasm → 神在心中 → 热情", list: "cet4-core", category: "high" },
  { id: 234, word: "environment", phonetic: "/ɪnˈvaɪrənmənt/", meaning: "n. 环境；周围状况",
    example: "We should protect the environment.", exampleCN: "我们应该保护环境。",
    tip: "environ(包围)+ment → 围住我们的一切 → 环境", list: "cet4-high", category: "high" },
  { id: 235, word: "equal", phonetic: "/ˈiːkwəl/", meaning: "adj. 相等的 v. 等于",
    example: "Everyone is equal before the law.", exampleCN: "法律面前人人平等。",
    tip: "equ(相等)+al → 相等的", list: "cet4-high", category: "high" },
  { id: 236, word: "equip", phonetic: "/ɪˈkwɪp/", meaning: "v. 装备；配备",
    example: "The lab is well equipped.", exampleCN: "这个实验室设备齐全。",
    tip: "equip → equipment(设备) 是不可数名词", list: "cet4-core", category: "high" },
  { id: 237, word: "essential", phonetic: "/ɪˈsenʃl/", meaning: "adj. 必要的；本质的",
    example: "Water is essential to life.", exampleCN: "水对生命必不可少。",
    tip: "ess(存在)+ential → 关乎存在的 → 必要的", list: "cet4-high", category: "high" },
  { id: 238, word: "establish", phonetic: "/ɪˈstæblɪʃ/", meaning: "v. 建立；确立",
    example: "They established a new company.", exampleCN: "他们成立了一家新公司。",
    tip: "e(出)+stabl(站稳)+ish → 站稳 → 建立", list: "cet4-high", category: "high" },
  { id: 239, word: "estimate", phonetic: "/ˈestɪmeɪt/", meaning: "v./n. 估计；评估",
    example: "I estimate it will take two hours.", exampleCN: "我估计这要花两个小时。",
    tip: "estim(价值)+ate → 估个价 → 估计", list: "cet4-high", category: "high" },
  { id: 240, word: "evaluate", phonetic: "/ɪˈvæljueɪt/", meaning: "v. 评估；评价",
    example: "The teacher evaluated our work.", exampleCN: "老师评估了我们的作业。",
    tip: "e(出)+valu(价值)+ate → 定出价值 → 评估", list: "cet4-core", category: "high" },
  { id: 241, word: "evidence", phonetic: "/ˈevɪdəns/", meaning: "n. 证据；迹象",
    example: "There is no evidence for that.", exampleCN: "那件事没有证据。",
    tip: "e(出)+vid(看)+ence → 看得见的东西 → 证据", list: "cet4-high", category: "high" },
  { id: 242, word: "exchange", phonetic: "/ɪksˈtʃeɪndʒ/", meaning: "n./v. 交换；交流",
    example: "We exchanged phone numbers.", exampleCN: "我们交换了电话号码。",
    tip: "ex(出)+change(换) → 换出去 → 交换", list: "cet4-high", category: "high" },
  { id: 243, word: "exhibit", phonetic: "/ɪɡˈzɪbɪt/", meaning: "v. 展出 n. 展品",
    example: "The gallery exhibits modern art.", exampleCN: "这家画廊展出当代艺术。",
    tip: "ex(出)+hibit(拿) → 拿出来给人看 → 展出", list: "cet4-core", category: "high" },
  { id: 244, word: "expand", phonetic: "/ɪkˈspænd/", meaning: "v. 扩大；膨胀",
    example: "Reading expands your world.", exampleCN: "阅读扩展你的世界。",
    tip: "ex(出)+pand(展开) → 展开 → 扩大", list: "cet4-high", category: "high" },
  { id: 245, word: "expense", phonetic: "/ɪkˈspens/", meaning: "n. 费用；开支",
    example: "Travel expenses are high.", exampleCN: "差旅费用很高。",
    tip: "ex(出)+pense(花钱) → 花出去的钱 → 费用", list: "cet4-high", category: "high" },
  { id: 246, word: "experiment", phonetic: "/ɪkˈsperɪmənt/", meaning: "n./v. 实验；试验",
    example: "We did an experiment in class.", exampleCN: "我们在课上做了一个实验。",
    tip: "ex(出)+peri(试)+ment → 试出来的结果 → 实验", list: "cet4-high", category: "high" },
  { id: 247, word: "explore", phonetic: "/ɪkˈsplɔː(r)/", meaning: "v. 探索；勘探",
    example: "Let's explore the old town.", exampleCN: "我们去探索这座老城吧。",
    tip: "ex(出)+plore(喊) → 出去呼喊探寻 → 探索", list: "cet4-high", category: "high" },
  { id: 248, word: "expose", phonetic: "/ɪkˈspəʊz/", meaning: "v. 暴露；使接触",
    example: "Don't expose your skin to the sun.", exampleCN: "别让皮肤暴晒在阳光下。",
    tip: "ex(出)+pose(放) → 放出来 → 暴露", list: "cet4-high", category: "high" },
  { id: 249, word: "express", phonetic: "/ɪkˈspres/", meaning: "v. 表达 adj. 快速的",
    example: "Express your ideas clearly.", exampleCN: "清楚地表达你的想法。",
    tip: "ex(出)+press(压) → 把想法压出来 → 表达", list: "cet4-high", category: "high" },
  { id: 250, word: "extend", phonetic: "/ɪkˈstend/", meaning: "v. 延伸；延长",
    example: "They extended the deadline.", exampleCN: "他们延长了截止日期。",
    tip: "ex(出)+tend(伸) → 伸出去 → 延长", list: "cet4-high", category: "high" },
  { id: 251, word: "external", phonetic: "/ɪkˈstɜːnl/", meaning: "adj. 外部的；外来的",
    example: "External factors also matter.", exampleCN: "外部因素也很重要。",
    tip: "extern(外)+al ↔ internal(内部的)", list: "cet4-core", category: "high" },
  { id: 252, word: "extreme", phonetic: "/ɪkˈstriːm/", meaning: "adj. 极端的 n. 极端",
    example: "The weather is extreme here.", exampleCN: "这里的天气很极端。",
    tip: "extr(超出)+eme → 超出常规 → 极端", list: "cet4-high", category: "high" },
  { id: 253, word: "facility", phonetic: "/fəˈsɪləti/", meaning: "n. 设施；便利",
    example: "The school has good sports facilities.", exampleCN: "这所学校有很好的体育设施。",
    tip: "fac(做)+ility → 让事情好做的东西 → 设施", list: "cet4-high", category: "high" },
  { id: 254, word: "factor", phonetic: "/ˈfæktə(r)/", meaning: "n. 因素；要素",
    example: "Money is not the only factor.", exampleCN: "钱不是唯一的因素。",
    tip: "fact(做)+or → 起作用的东西 → 因素", list: "cet4-high", category: "high" },
  { id: 255, word: "failure", phonetic: "/ˈfeɪljə(r)/", meaning: "n. 失败；故障",
    example: "Failure is the mother of success.", exampleCN: "失败是成功之母。",
    tip: "fail(失败)+ure → 失败", list: "cet4-high", category: "high" },
  { id: 256, word: "faith", phonetic: "/feɪθ/", meaning: "n. 信念；信任；信仰",
    example: "Have faith in yourself.", exampleCN: "要相信你自己。",
    tip: "形近 fair(公正) → 信任来自公正", list: "cet4-core", category: "high" },
  { id: 257, word: "familiar", phonetic: "/fəˈmɪliə(r)/", meaning: "adj. 熟悉的；常见的",
    example: "The song sounds familiar.", exampleCN: "这首歌听着耳熟。",
    tip: "famili(家庭)+ar → 像家人一样 → 熟悉", list: "cet4-high", category: "high" },
  { id: 258, word: "favorable", phonetic: "/ˈfeɪvərəbl/", meaning: "adj. 有利的；赞成的",
    example: "The conditions are favorable.", exampleCN: "条件很有利。",
    tip: "favor(赞成)+able → 值得赞成的 → 有利", list: "cet4-core", category: "high" },
  { id: 259, word: "feature", phonetic: "/ˈfiːtʃə(r)/", meaning: "n. 特征；特色 v. 以…为特色",
    example: "The main feature is its speed.", exampleCN: "主要特点是速度快。",
    tip: "feat(做)+ure → 做出来的样子 → 特征", list: "cet4-high", category: "high" },
  { id: 260, word: "figure", phonetic: "/ˈfɪɡə(r)/", meaning: "n. 数字；人物；身材 v. 认为",
    example: "The figures are not accurate.", exampleCN: "这些数字不准确。",
    tip: "一词多义：数字 / 人物 / 身材 / 想出", list: "cet4-high", category: "high" },
  { id: 261, word: "financial", phonetic: "/faɪˈnænʃl/", meaning: "adj. 财政的；金融的",
    example: "He is in financial trouble.", exampleCN: "他遇到了财务困难。",
    tip: "finance(财政)+ial → 财政的", list: "cet4-high", category: "high" },
  { id: 262, word: "flexible", phonetic: "/ˈfleksəbl/", meaning: "adj. 灵活的；易弯曲的",
    example: "My schedule is flexible.", exampleCN: "我的时间安排很灵活。",
    tip: "flex(弯曲)+ible → 能弯的 → 灵活", list: "cet4-high", category: "high" },
  { id: 263, word: "focus", phonetic: "/ˈfəʊkəs/", meaning: "v. 集中 n. 焦点；重点",
    example: "Focus on one task at a time.", exampleCN: "一次专注做一件事。",
    tip: "原义是“炉灶的火点” → 光聚于一点 → 焦点", list: "cet4-high", category: "high" },
  { id: 264, word: "forbid", phonetic: "/fəˈbɪd/", meaning: "v. 禁止；不许",
    example: "The law forbids smoking here.", exampleCN: "法律禁止在此吸烟。",
    tip: "for(否定)+bid(命令) → 下禁令 → 禁止", list: "cet4-high", category: "high" },
  { id: 265, word: "forecast", phonetic: "/ˈfɔːkɑːst/", meaning: "n./v. 预报；预测",
    example: "The forecast says rain tomorrow.", exampleCN: "预报说明天有雨。",
    tip: "fore(前)+cast(扔) → 提前扔出判断 → 预报", list: "cet4-high", category: "high" },
  { id: 266, word: "formal", phonetic: "/ˈfɔːml/", meaning: "adj. 正式的；正规的",
    example: "Wear formal clothes to the interview.", exampleCN: "面试要穿正装。",
    tip: "form(形式)+al → 讲形式的 → 正式", list: "cet4-high", category: "high" },
  { id: 267, word: "former", phonetic: "/ˈfɔːmə(r)/", meaning: "adj. 以前的；前者的",
    example: "The former is better than the latter.", exampleCN: "前者比后者好。",
    tip: "former(前者) ↔ latter(后者)，常成对出现", list: "cet4-high", category: "high" },
  { id: 268, word: "frequent", phonetic: "/ˈfriːkwənt/", meaning: "adj. 频繁的；经常的",
    example: "He is a frequent visitor.", exampleCN: "他是这里的常客。",
    tip: "freq(频繁)+uent → 频繁的", list: "cet4-high", category: "high" },
  { id: 269, word: "fundamental", phonetic: "/ˌfʌndəˈmentl/", meaning: "adj. 基本的；根本的",
    example: "Reading is a fundamental skill.", exampleCN: "阅读是一项基本技能。",
    tip: "fund(基础)+amental → 基础的", list: "cet4-core", category: "high" },
  { id: 270, word: "furniture", phonetic: "/ˈfɜːnɪtʃə(r)/", meaning: "n. 家具",
    example: "The room has little furniture.", exampleCN: "房间里家具很少。",
    tip: "不可数名词，没有复数形式，不能说 a furniture", list: "cet4-high", category: "high" },
  { id: 271, word: "gain", phonetic: "/ɡeɪn/", meaning: "v./n. 获得；增加",
    example: "He gained a lot from the trip.", exampleCN: "他从这次旅行中收获很多。",
    tip: "形近 again → 再来一次就得到了", list: "cet4-high", category: "high" },
  { id: 272, word: "gap", phonetic: "/ɡæp/", meaning: "n. 差距；缺口；间隔",
    example: "There is a gap between the two.", exampleCN: "两者之间存在差距。",
    tip: "形近 map → 地图上的空白处 → 缺口", list: "cet4-high", category: "high" },
  { id: 273, word: "gather", phonetic: "/ˈɡæðə(r)/", meaning: "v. 聚集；收集",
    example: "Students gathered in the hall.", exampleCN: "学生们聚集在大厅里。",
    tip: "形近 together → 到一起 → 聚集", list: "cet4-high", category: "high" },
  { id: 274, word: "generate", phonetic: "/ˈdʒenəreɪt/", meaning: "v. 产生；生成",
    example: "The plan generated new ideas.", exampleCN: "这个计划产生了新想法。",
    tip: "gener(产生)+ate → 产生", list: "cet4-high", category: "high" },
  { id: 275, word: "genuine", phonetic: "/ˈdʒenjuɪn/", meaning: "adj. 真正的；真诚的",
    example: "She showed genuine interest.", exampleCN: "她表现出真诚的兴趣。",
    tip: "gen(出生)+uine → 天生的 → 真正的", list: "cet4-core", category: "high" },
  { id: 276, word: "gradual", phonetic: "/ˈɡrædʒuəl/", meaning: "adj. 逐渐的；渐进的",
    example: "There was a gradual improvement.", exampleCN: "有了逐步的改善。",
    tip: "grad(步)+ual → 一步一步的 → 逐渐", list: "cet4-high", category: "high" },
  { id: 277, word: "grant", phonetic: "/ɡrɑːnt/", meaning: "v. 授予；同意 n. 补助金",
    example: "The school granted him a scholarship.", exampleCN: "学校授予他一笔奖学金。",
    tip: "形近 grand(大) → 大方地给 → 授予", list: "cet4-core", category: "high" },
  { id: 278, word: "guarantee", phonetic: "/ˌɡærənˈtiː/", meaning: "v./n. 保证；担保",
    example: "I can't guarantee the result.", exampleCN: "我不能保证结果。",
    tip: "guar(看守)+antee → 替你看着 → 担保", list: "cet4-high", category: "high" },
  { id: 279, word: "guilty", phonetic: "/ˈɡɪlti/", meaning: "adj. 有罪的；内疚的",
    example: "He felt guilty about lying.", exampleCN: "他因为撒谎而感到内疚。",
    tip: "guilt(罪)+y → 有罪的", list: "cet4-core", category: "high" },
  { id: 280, word: "handle", phonetic: "/ˈhændl/", meaning: "v. 处理；应对 n. 把手",
    example: "She handled the problem well.", exampleCN: "她把这个问题处理得很好。",
    tip: "hand(手)+le → 上手去处理", list: "cet4-high", category: "high" },
  { id: 281, word: "hardly", phonetic: "/ˈhɑːdli/", meaning: "adv. 几乎不；简直不",
    example: "I hardly know him.", exampleCN: "我几乎不认识他。",
    tip: "hard(难)+ly → 难到几乎不能 → 几乎不", list: "cet4-high", category: "high" },
  { id: 282, word: "harmony", phonetic: "/ˈhɑːməni/", meaning: "n. 和谐；融洽",
    example: "They live in harmony.", exampleCN: "他们和睦相处。",
    tip: "harmon(连接)+y → 连在一起 → 和谐", list: "cet4-core", category: "high" },
  { id: 283, word: "harvest", phonetic: "/ˈhɑːvɪst/", meaning: "n./v. 收获；收割",
    example: "The harvest was good this year.", exampleCN: "今年收成很好。",
    tip: "联想 have+rest → 收获之后才能休息", list: "cet4-core", category: "high" },
  { id: 284, word: "hesitate", phonetic: "/ˈhezɪteɪt/", meaning: "v. 犹豫；迟疑",
    example: "Don't hesitate to ask me.", exampleCN: "别犹豫，尽管问我。",
    tip: "hesit(粘住)+ate → 粘住不动 → 犹豫", list: "cet4-high", category: "high" },
  { id: 285, word: "honest", phonetic: "/ˈɒnɪst/", meaning: "adj. 诚实的；正直的",
    example: "Be honest with yourself.", exampleCN: "对自己要诚实。",
    tip: "h 不发音，读 /ˈɒnɪst/", list: "cet4-high", category: "high" },
  { id: 286, word: "horizon", phonetic: "/həˈraɪzn/", meaning: "n. 地平线；眼界",
    example: "Travel broadens your horizon.", exampleCN: "旅行能开阔眼界。",
    tip: "horiz(界限)+on → 天地的界限 → 地平线", list: "cet4-core", category: "high" },
  { id: 287, word: "identify", phonetic: "/aɪˈdentɪfaɪ/", meaning: "v. 识别；确认",
    example: "Can you identify the problem?", exampleCN: "你能找出问题所在吗？",
    tip: "ident(相同)+ify → 认出是同一个 → 识别", list: "cet4-high", category: "high" },
  { id: 288, word: "ignore", phonetic: "/ɪɡˈnɔː(r)/", meaning: "v. 忽视；不理会",
    example: "Don't ignore small mistakes.", exampleCN: "别忽视小的错误。",
    tip: "i(不)+gnore(知道) → 装作不知道 → 忽视", list: "cet4-high", category: "high" },
  { id: 289, word: "illustrate", phonetic: "/ˈɪləstreɪt/", meaning: "v. 说明；举例说明",
    example: "Let me illustrate with an example.", exampleCN: "让我举个例子来说明。",
    tip: "il(使)+lustr(光)+ate → 照亮 → 说明", list: "cet4-core", category: "high" },
  { id: 290, word: "impact", phonetic: "/ˈɪmpækt/", meaning: "n. 影响；冲击 v. 影响",
    example: "The book had a big impact on me.", exampleCN: "这本书对我影响很大。",
    tip: "im(向内)+pact(压) → 压进去 → 冲击", list: "cet4-high", category: "high" },
  { id: 291, word: "imply", phonetic: "/ɪmˈplaɪ/", meaning: "v. 暗示；意味着",
    example: "His tone implied disagreement.", exampleCN: "他的语气暗示他不同意。",
    tip: "im(向内)+ply(折) → 折在里面 → 暗示", list: "cet4-core", category: "high" },
  { id: 292, word: "impress", phonetic: "/ɪmˈpres/", meaning: "v. 使印象深刻",
    example: "Her speech impressed everyone.", exampleCN: "她的演讲让所有人印象深刻。",
    tip: "im(向内)+press(压) → 压进心里 → 留下印象", list: "cet4-high", category: "high" },
  { id: 293, word: "improve", phonetic: "/ɪmˈpruːv/", meaning: "v. 改善；提高",
    example: "Practice improves your speaking.", exampleCN: "练习能提高你的口语。",
    tip: "im(向内)+prove(好) → 变好 → 改善", list: "cet4-high", category: "high" },
  { id: 294, word: "include", phonetic: "/ɪnˈkluːd/", meaning: "v. 包括；包含",
    example: "The price includes breakfast.", exampleCN: "这个价格包含早餐。",
    tip: "in(内)+clude(关) → 关在里面 → 包括", list: "cet4-high", category: "high" },
  { id: 295, word: "increase", phonetic: "/ɪnˈkriːs/", meaning: "v./n. 增加；增长",
    example: "Prices increased sharply.", exampleCN: "价格急剧上涨。",
    tip: "in(向内)+crease(生长) ↔ decrease(减少)", list: "cet4-high", category: "high" },
  { id: 296, word: "independent", phonetic: "/ˌɪndɪˈpendənt/", meaning: "adj. 独立的；自主的",
    example: "She is financially independent.", exampleCN: "她经济上独立。",
    tip: "in(不)+depend(依赖)+ent → 不依赖 → 独立", list: "cet4-high", category: "high" },
  { id: 297, word: "indicate", phonetic: "/ˈɪndɪkeɪt/", meaning: "v. 表明；指出",
    example: "The data indicates a rise.", exampleCN: "数据表明在上升。",
    tip: "in(向内)+dic(说)+ate → 指出来 → 表明", list: "cet4-high", category: "high" },
  { id: 298, word: "individual", phonetic: "/ˌɪndɪˈvɪdʒuəl/", meaning: "adj. 个人的 n. 个人",
    example: "Each individual is different.", exampleCN: "每个人都是不同的。",
    tip: "in(不)+divid(分)+ual → 不可再分的 → 个人", list: "cet4-high", category: "high" },
  { id: 299, word: "industry", phonetic: "/ˈɪndəstri/", meaning: "n. 工业；行业；勤奋",
    example: "He works in the film industry.", exampleCN: "他在电影行业工作。",
    tip: "indus(在内)+try → 在里面忙碌 → 产业", list: "cet4-high", category: "high" },
  { id: 300, word: "inevitable", phonetic: "/ɪnˈevɪtəbl/", meaning: "adj. 不可避免的",
    example: "Change is inevitable.", exampleCN: "变化是不可避免的。",
    tip: "in(不)+evit(避开)+able → 避不开的 → 必然", list: "cet4-core", category: "high" },
  { id: 301, word: "influence", phonetic: "/ˈɪnfluəns/", meaning: "n./v. 影响；感化",
    example: "Parents influence their children.", exampleCN: "父母会影响孩子。",
    tip: "in(向内)+flu(流)+ence → 流进来 → 影响", list: "cet4-high", category: "high" },
  { id: 302, word: "inform", phonetic: "/ɪnˈfɔːm/", meaning: "v. 通知；告知",
    example: "Please inform me of any change.", exampleCN: "有任何变化请通知我。",
    tip: "in(向内)+form(形成) → 使你心里成形 → 告知", list: "cet4-high", category: "high" },
  { id: 303, word: "initial", phonetic: "/ɪˈnɪʃl/", meaning: "adj. 最初的；开始的",
    example: "My initial plan failed.", exampleCN: "我最初的计划失败了。",
    tip: "init(开始)+ial → 最初的", list: "cet4-high", category: "high" },
  { id: 304, word: "innocent", phonetic: "/ˈɪnəsnt/", meaning: "adj. 无辜的；天真的",
    example: "He is innocent of the crime.", exampleCN: "他在这桩案子里是无辜的。",
    tip: "in(不)+nocent(伤害) → 不伤人的 → 无辜", list: "cet4-core", category: "high" },
  { id: 305, word: "insist", phonetic: "/ɪnˈsɪst/", meaning: "v. 坚持；坚决要求",
    example: "She insisted on paying.", exampleCN: "她坚持要付钱。",
    tip: "in(加强)+sist(站) → 站定不动 → 坚持", list: "cet4-high", category: "high" },
  { id: 306, word: "inspire", phonetic: "/ɪnˈspaɪə(r)/", meaning: "v. 激励；启发",
    example: "His story inspired me.", exampleCN: "他的故事激励了我。",
    tip: "in(向内)+spire(呼吸) → 吹进一口气 → 启发", list: "cet4-core", category: "high" },
  { id: 307, word: "install", phonetic: "/ɪnˈstɔːl/", meaning: "v. 安装；任命",
    example: "Can you install this app?", exampleCN: "你能装一下这个应用吗？",
    tip: "in(内)+stall(位置) → 放进位置 → 安装", list: "cet4-high", category: "high" },
  { id: 308, word: "instance", phonetic: "/ˈɪnstəns/", meaning: "n. 例子；实例",
    example: "For instance, take this case.", exampleCN: "例如，就拿这个例子来说。",
    tip: "in(在)+stance(站) → 就摆在眼前 → 实例", list: "cet4-high", category: "high" },
  { id: 309, word: "instant", phonetic: "/ˈɪnstənt/", meaning: "adj. 立即的 n. 瞬间",
    example: "He gave an instant reply.", exampleCN: "他立刻作了回答。",
    tip: "in(不)+stant(站) → 不站着等 → 立即", list: "cet4-high", category: "high" },
  { id: 310, word: "institute", phonetic: "/ˈɪnstɪtjuːt/", meaning: "n. 学院；机构 v. 设立",
    example: "She studies at a research institute.", exampleCN: "她在一家研究所学习。",
    tip: "in(内)+stitute(建立) → 建立起来的机构", list: "cet4-core", category: "high" },
  { id: 311, word: "intend", phonetic: "/ɪnˈtend/", meaning: "v. 打算；意图",
    example: "I intend to finish it today.", exampleCN: "我打算今天做完。",
    tip: "in(向内)+tend(伸) → 心思伸向 → 打算", list: "cet4-high", category: "high" },
  { id: 312, word: "interpret", phonetic: "/ɪnˈtɜːprɪt/", meaning: "v. 解释；口译",
    example: "How do you interpret this line?", exampleCN: "你怎么理解这一句？",
    tip: "inter(之间)+pret(说) → 在中间说 → 口译", list: "cet4-core", category: "high" },
  { id: 313, word: "invest", phonetic: "/ɪnˈvest/", meaning: "v. 投资；投入",
    example: "He invested in a small shop.", exampleCN: "他投资了一家小店。",
    tip: "in(内)+vest(衣服) → 穿上 → 把钱投进去", list: "cet4-high", category: "high" },
  { id: 314, word: "involve", phonetic: "/ɪnˈvɒlv/", meaning: "v. 涉及；使参与",
    example: "The job involves a lot of travel.", exampleCN: "这份工作需要经常出差。",
    tip: "in(向内)+volve(卷) → 卷进去 → 涉及", list: "cet4-high", category: "high" },
  { id: 315, word: "isolate", phonetic: "/ˈaɪsəleɪt/", meaning: "v. 隔离；孤立",
    example: "Patients were isolated.", exampleCN: "病人被隔离了。",
    tip: "isol(岛)+ate → 变成孤岛 → 隔离", list: "cet4-core", category: "high" },
  { id: 316, word: "issue", phonetic: "/ˈɪʃuː/", meaning: "n. 问题；期号 v. 发布",
    example: "This is a serious issue.", exampleCN: "这是个严重的问题。",
    tip: "一词多义：问题 / 期号 / 发行", list: "cet4-high", category: "high" },
  { id: 317, word: "judge", phonetic: "/dʒʌdʒ/", meaning: "v. 判断；评判 n. 法官",
    example: "Don't judge a book by its cover.", exampleCN: "不要以貌取人。",
    tip: "jud(判断)+ge → 判断", list: "cet4-high", category: "high" },
  { id: 318, word: "justify", phonetic: "/ˈdʒʌstɪfaɪ/", meaning: "v. 证明…正当；辩护",
    example: "Nothing can justify such behavior.", exampleCN: "这种行为无论如何都无法辩解。",
    tip: "just(正当)+ify → 使正当 → 辩护", list: "cet4-core", category: "high" },
  { id: 319, word: "labor", phonetic: "/ˈleɪbə(r)/", meaning: "n. 劳动；劳工 v. 劳动",
    example: "The work requires hard labor.", exampleCN: "这项工作需要艰苦的劳动。",
    tip: "lab(劳动)+or → 劳动（美式拼写，英式 labour）", list: "cet4-core", category: "high" },
  { id: 320, word: "launch", phonetic: "/lɔːntʃ/", meaning: "v. 发射；发起；推出",
    example: "They launched a new product.", exampleCN: "他们推出了一款新产品。",
    tip: "形近 lunch → 吃完午饭就发射", list: "cet4-high", category: "high" },
  { id: 321, word: "leak", phonetic: "/liːk/", meaning: "v. 泄漏 n. 漏洞",
    example: "The roof leaks when it rains.", exampleCN: "下雨时屋顶会漏水。",
    tip: "形近 lake → 湖里的水漏出来", list: "cet4-core", category: "high" },
  { id: 322, word: "legal", phonetic: "/ˈliːɡl/", meaning: "adj. 合法的；法律的",
    example: "Is it legal to park here?", exampleCN: "在这里停车合法吗？",
    tip: "leg(法律)+al → 合法的 ↔ illegal(非法的)", list: "cet4-high", category: "high" },
  { id: 323, word: "license", phonetic: "/ˈlaɪsns/", meaning: "n. 执照；许可证 v. 许可",
    example: "He got his driver's license.", exampleCN: "他拿到了驾照。",
    tip: "lic(允许)+ense → 允许 → 执照", list: "cet4-high", category: "high" },
  { id: 324, word: "limit", phonetic: "/ˈlɪmɪt/", meaning: "n. 限度 v. 限制",
    example: "Limit your time on the phone.", exampleCN: "限制你玩手机的时间。",
    tip: "lim(界限)+it → 界限 → 限制", list: "cet4-high", category: "high" },
  { id: 325, word: "link", phonetic: "/lɪŋk/", meaning: "v. 连接 n. 联系；链接",
    example: "The bridge links the two cities.", exampleCN: "这座桥连接两座城市。",
    tip: "形近 line → 一条线连起来 → 连接", list: "cet4-high", category: "high" },
  { id: 326, word: "locate", phonetic: "/ləʊˈkeɪt/", meaning: "v. 位于；找出…的位置",
    example: "The school is located near the park.", exampleCN: "学校位于公园附近。",
    tip: "loc(地方)+ate → 定位置 → 位于", list: "cet4-high", category: "high" },
  { id: 327, word: "maintain", phonetic: "/meɪnˈteɪn/", meaning: "v. 维持；保养；主张",
    example: "It is hard to maintain such a speed.", exampleCN: "很难维持这样的速度。",
    tip: "main(手)+tain(握) → 用手一直握着 → 维持", list: "cet4-high", category: "high" },
  { id: 328, word: "major", phonetic: "/ˈmeɪdʒə(r)/", meaning: "adj. 主要的 n. 专业 v. 主修",
    example: "Her major is English.", exampleCN: "她的专业是英语。",
    tip: "maj(大)+or → 大的 → 主要的/专业", list: "cet4-high", category: "high" },
  { id: 329, word: "manufacture", phonetic: "/ˌmænjuˈfæktʃə(r)/", meaning: "v./n. 制造；生产",
    example: "The factory manufactures cars.", exampleCN: "这家工厂生产汽车。",
    tip: "manu(手)+fact(做)+ure → 用手做 → 制造", list: "cet4-core", category: "high" },
  { id: 330, word: "mature", phonetic: "/məˈtʃʊə(r)/", meaning: "adj. 成熟的 v. 成熟",
    example: "She is very mature for her age.", exampleCN: "以她的年龄来说她很成熟。",
    tip: "mat(成熟)+ure → 成熟的", list: "cet4-core", category: "high" },
  { id: 331, word: "means", phonetic: "/miːnz/", meaning: "n. 方法；手段；财产",
    example: "Try every means to solve it.", exampleCN: "用尽一切办法解决它。",
    tip: "单复数同形：a means / two means", list: "cet4-high", category: "high" },
  { id: 332, word: "measure", phonetic: "/ˈmeʒə(r)/", meaning: "v. 测量 n. 措施；尺寸",
    example: "We should take measures to save water.", exampleCN: "我们应该采取措施节约用水。",
    tip: "meas(测量)+ure → 测量 → 措施", list: "cet4-high", category: "high" },
  { id: 333, word: "military", phonetic: "/ˈmɪlətri/", meaning: "adj. 军事的 n. 军队",
    example: "He joined the military last year.", exampleCN: "他去年参军了。",
    tip: "milit(士兵)+ary → 士兵的 → 军事的", list: "cet4-core", category: "high" },
  { id: 334, word: "minor", phonetic: "/ˈmaɪnə(r)/", meaning: "adj. 次要的；较小的 n. 辅修",
    example: "It is only a minor problem.", exampleCN: "这只是个小问题。",
    tip: "min(小)+or ↔ major(主要的)", list: "cet4-high", category: "high" },
  { id: 335, word: "modify", phonetic: "/ˈmɒdɪfaɪ/", meaning: "v. 修改；调整",
    example: "We need to modify the plan.", exampleCN: "我们需要修改一下计划。",
    tip: "mod(方式)+ify → 改方式 → 修改", list: "cet4-core", category: "high" },
  { id: 336, word: "motive", phonetic: "/ˈməʊtɪv/", meaning: "n. 动机；目的",
    example: "What is his motive for helping?", exampleCN: "他帮忙的动机是什么？",
    tip: "mot(移动)+ive → 推动你动的 → 动机", list: "cet4-core", category: "high" },
];
